// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogWithValues = `-- name: CreateAuditLogWithValues :one
INSERT INTO "AuditLog" (
    id,
    "userId",
    action,
    "entityType",
    "entityId",
    "oldValues",
    "newValues"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type CreateAuditLogWithValuesParams struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Action     string      `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.Text `json:"entity_id"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
}

func (q *Queries) CreateAuditLogWithValues(ctx context.Context, arg CreateAuditLogWithValuesParams) (string, error) {
	row := q.db.QueryRow(ctx, createAuditLogWithValues,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
