// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*)::bigint AS count FROM "Role"
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS count FROM "User"
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO "AuditLog" (id, "userId", action, "entityType", "entityId")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "userId", action, "entityType", "entityId", "createdAt"
`

type CreateAuditLogParams struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Action     string      `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.Text `json:"entity_id"`
}

type CreateAuditLogRow struct {
	ID         string           `json:"id"`
	UserId     string           `json:"userId"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entityType"`
	EntityId   pgtype.Text      `json:"entityId"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
	)
	var i CreateAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Action,
		&i.EntityType,
		&i.EntityId,
		&i.CreatedAt,
	)
	return i, err
}

const getModulePermissionByRoleCode = `-- name: GetModulePermissionByRoleCode :one
SELECT p.access
FROM "RoleModulePermission" p
INNER JOIN "Role" r ON r.id = p."roleId"
WHERE r.code = $1 AND p.module = $2
`

type GetModulePermissionByRoleCodeParams struct {
	RoleCode string `json:"role_code"`
	Module   string `json:"module"`
}

func (q *Queries) GetModulePermissionByRoleCode(ctx context.Context, arg GetModulePermissionByRoleCodeParams) (ModuleAccess, error) {
	row := q.db.QueryRow(ctx, getModulePermissionByRoleCode, arg.RoleCode, arg.Module)
	var access ModuleAccess
	err := row.Scan(&access)
	return access, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    u.id,
    u.email,
    u."passwordHash",
    u."fullName",
    u."isActive",
    u."roleId",
    r.code AS role_code,
    r.name AS role_name
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE LOWER(u.email) = LOWER($1)
`

type GetUserByEmailRow struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	FullName     string `json:"fullName"`
	IsActive     bool   `json:"isActive"`
	RoleId       string `json:"roleId"`
	RoleCode     string `json:"role_code"`
	RoleName     string `json:"role_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.RoleId,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id,
    u.email,
    u."passwordHash",
    u."fullName",
    u."isActive",
    u."roleId",
    r.code AS role_code,
    r.name AS role_name
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	FullName     string `json:"fullName"`
	IsActive     bool   `json:"isActive"`
	RoleId       string `json:"roleId"`
	RoleCode     string `json:"role_code"`
	RoleName     string `json:"role_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.RoleId,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const listPermissionsByRoleID = `-- name: ListPermissionsByRoleID :many
SELECT module, access
FROM "RoleModulePermission"
WHERE "roleId" = $1
`

type ListPermissionsByRoleIDRow struct {
	Module string       `json:"module"`
	Access ModuleAccess `json:"access"`
}

func (q *Queries) ListPermissionsByRoleID(ctx context.Context, roleID string) ([]ListPermissionsByRoleIDRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsByRoleIDRow{}
	for rows.Next() {
		var i ListPermissionsByRoleIDRow
		if err := rows.Scan(&i.Module, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::int AS val
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var val int32
	err := row.Scan(&val)
	return val, err
}
