// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coils.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCoil = `-- name: ArchiveCoil :one
UPDATE "Coil"
SET
    status = 'ARCHIVED',
    "archivedAt" = NOW(),
    "archivedById" = $1,
    "updatedAt" = NOW()
WHERE "coilNumber" = $2
RETURNING "coilNumber", grade, coating, size, weight, supplier, "mtcNumber", "invoiceNumber", "amnsDispatchDate", "vehicleNumber", "transporterName", "receiptDateSlitter", "receivingConditionRemarks", status, "archivedAt", "archivedById", "createdAt", "updatedAt"
`

type ArchiveCoilParams struct {
	ArchivedByID pgtype.Text `json:"archived_by_id"`
	CoilNumber   string      `json:"coil_number"`
}

func (q *Queries) ArchiveCoil(ctx context.Context, arg ArchiveCoilParams) (Coil, error) {
	row := q.db.QueryRow(ctx, archiveCoil, arg.ArchivedByID, arg.CoilNumber)
	var i Coil
	err := row.Scan(
		&i.CoilNumber,
		&i.Grade,
		&i.Coating,
		&i.Size,
		&i.Weight,
		&i.Supplier,
		&i.MtcNumber,
		&i.InvoiceNumber,
		&i.AmnsDispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ReceiptDateSlitter,
		&i.ReceivingConditionRemarks,
		&i.Status,
		&i.ArchivedAt,
		&i.ArchivedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const coilExists = `-- name: CoilExists :one
SELECT EXISTS(SELECT 1 FROM "Coil" WHERE "coilNumber" = $1)::bool AS exists
`

func (q *Queries) CoilExists(ctx context.Context, coilNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, coilExists, coilNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveCoils = `-- name: CountActiveCoils :one
SELECT COUNT(*)::bigint AS count FROM "Coil" WHERE status = 'ACTIVE'
`

func (q *Queries) CountActiveCoils(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCoils)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCoilsInTrace = `-- name: CountActiveCoilsInTrace :one
SELECT COUNT(DISTINCT c."coilNumber")::bigint AS count
FROM "Coil" c
INNER JOIN "SlittingRecord" sr ON sr."parentCoilNumber" = c."coilNumber"
WHERE c.status = 'ACTIVE'
`

func (q *Queries) CountActiveCoilsInTrace(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCoilsInTrace)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCoilsWithDocs = `-- name: CountActiveCoilsWithDocs :one
SELECT COUNT(DISTINCT c."coilNumber")::bigint AS count
FROM "Coil" c
INNER JOIN "CoilDocument" d ON d."coilNumber" = c."coilNumber"
WHERE c.status = 'ACTIVE'
`

func (q *Queries) CountActiveCoilsWithDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCoilsWithDocs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllCoils = `-- name: CountAllCoils :one
SELECT COUNT(*)::bigint AS count FROM "Coil"
`

func (q *Queries) CountAllCoils(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCoils)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllCoilsInTrace = `-- name: CountAllCoilsInTrace :one
SELECT COUNT(DISTINCT c."coilNumber")::bigint AS count
FROM "Coil" c
INNER JOIN "SlittingRecord" sr ON sr."parentCoilNumber" = c."coilNumber"
`

func (q *Queries) CountAllCoilsInTrace(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCoilsInTrace)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllCoilsWithDocs = `-- name: CountAllCoilsWithDocs :one
SELECT COUNT(DISTINCT c."coilNumber")::bigint AS count
FROM "Coil" c
INNER JOIN "CoilDocument" d ON d."coilNumber" = c."coilNumber"
`

func (q *Queries) CountAllCoilsWithDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCoilsWithDocs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedCoils = `-- name: CountArchivedCoils :one
SELECT COUNT(*)::bigint AS count FROM "Coil" WHERE status = 'ARCHIVED'
`

func (q *Queries) CountArchivedCoils(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedCoils)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByCoil = `-- name: CountDocumentsByCoil :one
SELECT COUNT(*)::bigint AS count
FROM "CoilDocument"
WHERE "coilNumber" = $1
`

func (q *Queries) CountDocumentsByCoil(ctx context.Context, coilNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByCoil, coilNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSlittingByCoil = `-- name: CountSlittingByCoil :one
SELECT COUNT(*)::bigint AS count
FROM "SlittingRecord"
WHERE "parentCoilNumber" = $1
`

func (q *Queries) CountSlittingByCoil(ctx context.Context, coilNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countSlittingByCoil, coilNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoil = `-- name: CreateCoil :one
INSERT INTO "Coil" (
    "coilNumber",
    grade,
    coating,
    size,
    weight,
    supplier,
    "mtcNumber",
    "invoiceNumber",
    "amnsDispatchDate",
    "vehicleNumber",
    "transporterName",
    "receiptDateSlitter",
    "receivingConditionRemarks",
    status,
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, 'AMNS (Hazira Plant)'),
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    'ACTIVE',
    NOW(),
    NOW()
)
RETURNING "coilNumber", grade, coating, size, weight, supplier, "mtcNumber", "invoiceNumber", "amnsDispatchDate", "vehicleNumber", "transporterName", "receiptDateSlitter", "receivingConditionRemarks", status, "archivedAt", "archivedById", "createdAt", "updatedAt"
`

type CreateCoilParams struct {
	CoilNumber                string           `json:"coil_number"`
	Grade                     string           `json:"grade"`
	Coating                   string           `json:"coating"`
	Size                      string           `json:"size"`
	Weight                    pgtype.Numeric   `json:"weight"`
	Supplier                  interface{}      `json:"supplier"`
	MtcNumber                 pgtype.Text      `json:"mtc_number"`
	InvoiceNumber             pgtype.Text      `json:"invoice_number"`
	AmnsDispatchDate          pgtype.Timestamp `json:"amns_dispatch_date"`
	VehicleNumber             pgtype.Text      `json:"vehicle_number"`
	TransporterName           pgtype.Text      `json:"transporter_name"`
	ReceiptDateSlitter        pgtype.Timestamp `json:"receipt_date_slitter"`
	ReceivingConditionRemarks pgtype.Text      `json:"receiving_condition_remarks"`
}

func (q *Queries) CreateCoil(ctx context.Context, arg CreateCoilParams) (Coil, error) {
	row := q.db.QueryRow(ctx, createCoil,
		arg.CoilNumber,
		arg.Grade,
		arg.Coating,
		arg.Size,
		arg.Weight,
		arg.Supplier,
		arg.MtcNumber,
		arg.InvoiceNumber,
		arg.AmnsDispatchDate,
		arg.VehicleNumber,
		arg.TransporterName,
		arg.ReceiptDateSlitter,
		arg.ReceivingConditionRemarks,
	)
	var i Coil
	err := row.Scan(
		&i.CoilNumber,
		&i.Grade,
		&i.Coating,
		&i.Size,
		&i.Weight,
		&i.Supplier,
		&i.MtcNumber,
		&i.InvoiceNumber,
		&i.AmnsDispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ReceiptDateSlitter,
		&i.ReceivingConditionRemarks,
		&i.Status,
		&i.ArchivedAt,
		&i.ArchivedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoilDocument = `-- name: CreateCoilDocument :one
INSERT INTO "CoilDocument" (
    id,
    "coilNumber",
    "documentType",
    filename,
    "originalName",
    mimetype,
    size,
    "storagePath",
    "uploadedById",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    NOW()
)
RETURNING id, "coilNumber", "documentType", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
`

type CreateCoilDocumentParams struct {
	ID           string           `json:"id"`
	CoilNumber   string           `json:"coil_number"`
	DocumentType CoilDocumentType `json:"document_type"`
	Filename     string           `json:"filename"`
	OriginalName string           `json:"original_name"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	StoragePath  string           `json:"storage_path"`
	UploadedByID pgtype.Text      `json:"uploaded_by_id"`
}

func (q *Queries) CreateCoilDocument(ctx context.Context, arg CreateCoilDocumentParams) (CoilDocument, error) {
	row := q.db.QueryRow(ctx, createCoilDocument,
		arg.ID,
		arg.CoilNumber,
		arg.DocumentType,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
		arg.StoragePath,
		arg.UploadedByID,
	)
	var i CoilDocument
	err := row.Scan(
		&i.ID,
		&i.CoilNumber,
		&i.DocumentType,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoil = `-- name: DeleteCoil :exec
DELETE FROM "Coil" WHERE "coilNumber" = $1
`

func (q *Queries) DeleteCoil(ctx context.Context, coilNumber string) error {
	_, err := q.db.Exec(ctx, deleteCoil, coilNumber)
	return err
}

const deleteCoilDocument = `-- name: DeleteCoilDocument :exec
DELETE FROM "CoilDocument" WHERE id = $1
`

func (q *Queries) DeleteCoilDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCoilDocument, id)
	return err
}

const getCoilByNumber = `-- name: GetCoilByNumber :one
SELECT "coilNumber", grade, coating, size, weight, supplier, "mtcNumber", "invoiceNumber", "amnsDispatchDate", "vehicleNumber", "transporterName", "receiptDateSlitter", "receivingConditionRemarks", status, "archivedAt", "archivedById", "createdAt", "updatedAt"
FROM "Coil"
WHERE "coilNumber" = $1
`

func (q *Queries) GetCoilByNumber(ctx context.Context, coilNumber string) (Coil, error) {
	row := q.db.QueryRow(ctx, getCoilByNumber, coilNumber)
	var i Coil
	err := row.Scan(
		&i.CoilNumber,
		&i.Grade,
		&i.Coating,
		&i.Size,
		&i.Weight,
		&i.Supplier,
		&i.MtcNumber,
		&i.InvoiceNumber,
		&i.AmnsDispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ReceiptDateSlitter,
		&i.ReceivingConditionRemarks,
		&i.Status,
		&i.ArchivedAt,
		&i.ArchivedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoilDocumentByID = `-- name: GetCoilDocumentByID :one
SELECT id, "coilNumber", "documentType", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "CoilDocument"
WHERE id = $1
`

func (q *Queries) GetCoilDocumentByID(ctx context.Context, id string) (CoilDocument, error) {
	row := q.db.QueryRow(ctx, getCoilDocumentByID, id)
	var i CoilDocument
	err := row.Scan(
		&i.ID,
		&i.CoilNumber,
		&i.DocumentType,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const getCoilUsageGraphRows = `-- name: GetCoilUsageGraphRows :many
SELECT
    sr."slitCoilId",
    srr.id AS sunrack_receipt_id,
    bcm."batchNumber",
    dbl."dispatchNoteNumber",
    si.id AS installation_id,
    cbl."complaintId"
FROM "SlittingRecord" sr
LEFT JOIN "SunrackReceipt" srr ON srr."slitCoilId" = sr."slitCoilId"
LEFT JOIN "BatchSlitCoilMap" bcm ON bcm."slitCoilId" = sr."slitCoilId"
LEFT JOIN "DispatchBatchLine" dbl ON dbl."batchNumber" = bcm."batchNumber"
LEFT JOIN "SiteInstallation" si ON si."dispatchNoteNumber" = dbl."dispatchNoteNumber"
LEFT JOIN "ComplaintBatchLine" cbl ON cbl."batchNumber" = bcm."batchNumber"
WHERE sr."parentCoilNumber" = $1
`

type GetCoilUsageGraphRowsRow struct {
	SlitCoilId         string      `json:"slitCoilId"`
	SunrackReceiptID   pgtype.Text `json:"sunrack_receipt_id"`
	BatchNumber        pgtype.Text `json:"batchNumber"`
	DispatchNoteNumber pgtype.Text `json:"dispatchNoteNumber"`
	InstallationID     pgtype.Text `json:"installation_id"`
	ComplaintId        pgtype.Text `json:"complaintId"`
}

func (q *Queries) GetCoilUsageGraphRows(ctx context.Context, coilNumber string) ([]GetCoilUsageGraphRowsRow, error) {
	rows, err := q.db.Query(ctx, getCoilUsageGraphRows, coilNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoilUsageGraphRowsRow{}
	for rows.Next() {
		var i GetCoilUsageGraphRowsRow
		if err := rows.Scan(
			&i.SlitCoilId,
			&i.SunrackReceiptID,
			&i.BatchNumber,
			&i.DispatchNoteNumber,
			&i.InstallationID,
			&i.ComplaintId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoilAuditLogs = `-- name: ListCoilAuditLogs :many
SELECT
    al.id,
    al.action,
    al."entityType",
    al."entityId",
    al."oldValues",
    al."newValues",
    al."createdAt",
    u."fullName",
    u.email,
    r.name AS role_name
FROM "AuditLog" al
INNER JOIN "User" u ON u.id = al."userId"
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE (
    (al."entityType" = 'Coil' AND al."entityId" = $1)
    OR (
        al."entityType" = 'CoilDocument'
        AND al."entityId" = ANY($2::text[])
    )
)
ORDER BY al."createdAt" DESC
LIMIT $3
`

type ListCoilAuditLogsParams struct {
	CoilNumber  pgtype.Text `json:"coil_number"`
	DocumentIds []string    `json:"document_ids"`
	RowLimit    int32       `json:"row_limit"`
}

type ListCoilAuditLogsRow struct {
	ID         string           `json:"id"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entityType"`
	EntityId   pgtype.Text      `json:"entityId"`
	OldValues  []byte           `json:"oldValues"`
	NewValues  []byte           `json:"newValues"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	FullName   string           `json:"fullName"`
	Email      string           `json:"email"`
	RoleName   string           `json:"role_name"`
}

func (q *Queries) ListCoilAuditLogs(ctx context.Context, arg ListCoilAuditLogsParams) ([]ListCoilAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listCoilAuditLogs, arg.CoilNumber, arg.DocumentIds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoilAuditLogsRow{}
	for rows.Next() {
		var i ListCoilAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityId,
			&i.OldValues,
			&i.NewValues,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoilDocumentIDs = `-- name: ListCoilDocumentIDs :many
SELECT id
FROM "CoilDocument"
WHERE "coilNumber" = $1
`

func (q *Queries) ListCoilDocumentIDs(ctx context.Context, coilNumber string) ([]string, error) {
	rows, err := q.db.Query(ctx, listCoilDocumentIDs, coilNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoilDocuments = `-- name: ListCoilDocuments :many
SELECT id, "coilNumber", "documentType", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "CoilDocument"
WHERE "coilNumber" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListCoilDocuments(ctx context.Context, coilNumber string) ([]CoilDocument, error) {
	rows, err := q.db.Query(ctx, listCoilDocuments, coilNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoilDocument{}
	for rows.Next() {
		var i CoilDocument
		if err := rows.Scan(
			&i.ID,
			&i.CoilNumber,
			&i.DocumentType,
			&i.Filename,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.StoragePath,
			&i.UploadedById,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlittingByCoil = `-- name: ListSlittingByCoil :many
SELECT "slitCoilId", "parentCoilNumber", "slitWidthSize", "slittingDate", "slitCoilWeight", "slitterLocation", "dispatchNote", "vehicleNumber", "transporterName", "createdAt", "updatedAt"
FROM "SlittingRecord"
WHERE "parentCoilNumber" = $1
ORDER BY "slittingDate" DESC
`

func (q *Queries) ListSlittingByCoil(ctx context.Context, coilNumber string) ([]SlittingRecord, error) {
	rows, err := q.db.Query(ctx, listSlittingByCoil, coilNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlittingRecord{}
	for rows.Next() {
		var i SlittingRecord
		if err := rows.Scan(
			&i.SlitCoilId,
			&i.ParentCoilNumber,
			&i.SlitWidthSize,
			&i.SlittingDate,
			&i.SlitCoilWeight,
			&i.SlitterLocation,
			&i.DispatchNote,
			&i.VehicleNumber,
			&i.TransporterName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoil = `-- name: UpdateCoil :one
UPDATE "Coil"
SET
    grade = COALESCE($1, grade),
    coating = COALESCE($2, coating),
    size = COALESCE($3, size),
    weight = COALESCE($4, weight),
    supplier = COALESCE($5, supplier),
    "mtcNumber" = COALESCE($6, "mtcNumber"),
    "invoiceNumber" = COALESCE($7, "invoiceNumber"),
    "amnsDispatchDate" = COALESCE($8, "amnsDispatchDate"),
    "vehicleNumber" = COALESCE($9, "vehicleNumber"),
    "transporterName" = COALESCE($10, "transporterName"),
    "receiptDateSlitter" = COALESCE($11, "receiptDateSlitter"),
    "receivingConditionRemarks" = COALESCE($12, "receivingConditionRemarks"),
    "updatedAt" = NOW()
WHERE "coilNumber" = $13
RETURNING "coilNumber", grade, coating, size, weight, supplier, "mtcNumber", "invoiceNumber", "amnsDispatchDate", "vehicleNumber", "transporterName", "receiptDateSlitter", "receivingConditionRemarks", status, "archivedAt", "archivedById", "createdAt", "updatedAt"
`

type UpdateCoilParams struct {
	Grade                     pgtype.Text      `json:"grade"`
	Coating                   pgtype.Text      `json:"coating"`
	Size                      pgtype.Text      `json:"size"`
	Weight                    pgtype.Numeric   `json:"weight"`
	Supplier                  pgtype.Text      `json:"supplier"`
	MtcNumber                 pgtype.Text      `json:"mtc_number"`
	InvoiceNumber             pgtype.Text      `json:"invoice_number"`
	AmnsDispatchDate          pgtype.Timestamp `json:"amns_dispatch_date"`
	VehicleNumber             pgtype.Text      `json:"vehicle_number"`
	TransporterName           pgtype.Text      `json:"transporter_name"`
	ReceiptDateSlitter        pgtype.Timestamp `json:"receipt_date_slitter"`
	ReceivingConditionRemarks pgtype.Text      `json:"receiving_condition_remarks"`
	CoilNumber                string           `json:"coil_number"`
}

func (q *Queries) UpdateCoil(ctx context.Context, arg UpdateCoilParams) (Coil, error) {
	row := q.db.QueryRow(ctx, updateCoil,
		arg.Grade,
		arg.Coating,
		arg.Size,
		arg.Weight,
		arg.Supplier,
		arg.MtcNumber,
		arg.InvoiceNumber,
		arg.AmnsDispatchDate,
		arg.VehicleNumber,
		arg.TransporterName,
		arg.ReceiptDateSlitter,
		arg.ReceivingConditionRemarks,
		arg.CoilNumber,
	)
	var i Coil
	err := row.Scan(
		&i.CoilNumber,
		&i.Grade,
		&i.Coating,
		&i.Size,
		&i.Weight,
		&i.Supplier,
		&i.MtcNumber,
		&i.InvoiceNumber,
		&i.AmnsDispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ReceiptDateSlitter,
		&i.ReceivingConditionRemarks,
		&i.Status,
		&i.ArchivedAt,
		&i.ArchivedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
