// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complaint.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const complaintExists = `-- name: ComplaintExists :one
SELECT EXISTS(
    SELECT 1 FROM "Complaint" WHERE "complaintId" = $1
) AS exists
`

func (q *Queries) ComplaintExists(ctx context.Context, complaintID string) (bool, error) {
	row := q.db.QueryRow(ctx, complaintExists, complaintID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countComplaintPhotos = `-- name: CountComplaintPhotos :one
SELECT COUNT(*)::bigint AS count FROM "ComplaintPhoto"
`

func (q *Queries) CountComplaintPhotos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaintPhotos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComplaintPhotosByComplaintID = `-- name: CountComplaintPhotosByComplaintID :one
SELECT COUNT(*)::bigint AS count
FROM "ComplaintPhoto"
WHERE "complaintId" = $1
`

func (q *Queries) CountComplaintPhotosByComplaintID(ctx context.Context, complaintID string) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaintPhotosByComplaintID, complaintID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComplaints = `-- name: CountComplaints :one
SELECT COUNT(*)::bigint AS count FROM "Complaint"
`

func (q *Queries) CountComplaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComplaintsByStatus = `-- name: CountComplaintsByStatus :one
SELECT COUNT(*)::bigint AS count
FROM "Complaint"
WHERE "resolutionStatus" = $1
`

func (q *Queries) CountComplaintsByStatus(ctx context.Context, resolutionStatus ResolutionStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaintsByStatus, resolutionStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO "Complaint" (
    "complaintId",
    "complaintDate",
    "projectName",
    "clientName",
    "siteLocation",
    "complaintDescription",
    "rootCauseRemarks",
    "resolutionStatus",
    "resolutionDate",
    "responsibleStage",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    NOW(),
    NOW()
)
RETURNING "complaintId", "complaintDate", "projectName", "clientName", "siteLocation", "complaintDescription", "rootCauseRemarks", "resolutionStatus", "resolutionDate", "responsibleStage", "createdAt", "updatedAt"
`

type CreateComplaintParams struct {
	ComplaintID          string               `json:"complaint_id"`
	ComplaintDate        pgtype.Timestamp     `json:"complaint_date"`
	ProjectName          string               `json:"project_name"`
	ClientName           string               `json:"client_name"`
	SiteLocation         string               `json:"site_location"`
	ComplaintDescription string               `json:"complaint_description"`
	RootCauseRemarks     pgtype.Text          `json:"root_cause_remarks"`
	ResolutionStatus     ResolutionStatus     `json:"resolution_status"`
	ResolutionDate       pgtype.Timestamp     `json:"resolution_date"`
	ResponsibleStage     NullResponsibleStage `json:"responsible_stage"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, createComplaint,
		arg.ComplaintID,
		arg.ComplaintDate,
		arg.ProjectName,
		arg.ClientName,
		arg.SiteLocation,
		arg.ComplaintDescription,
		arg.RootCauseRemarks,
		arg.ResolutionStatus,
		arg.ResolutionDate,
		arg.ResponsibleStage,
	)
	var i Complaint
	err := row.Scan(
		&i.ComplaintId,
		&i.ComplaintDate,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.ComplaintDescription,
		&i.RootCauseRemarks,
		&i.ResolutionStatus,
		&i.ResolutionDate,
		&i.ResponsibleStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createComplaintBatchLine = `-- name: CreateComplaintBatchLine :one
INSERT INTO "ComplaintBatchLine" (id, "complaintId", "batchNumber", "createdAt")
VALUES ($1, $2, $3, NOW())
RETURNING id, "complaintId", "batchNumber", "createdAt"
`

type CreateComplaintBatchLineParams struct {
	ID          string `json:"id"`
	ComplaintID string `json:"complaint_id"`
	BatchNumber string `json:"batch_number"`
}

func (q *Queries) CreateComplaintBatchLine(ctx context.Context, arg CreateComplaintBatchLineParams) (ComplaintBatchLine, error) {
	row := q.db.QueryRow(ctx, createComplaintBatchLine, arg.ID, arg.ComplaintID, arg.BatchNumber)
	var i ComplaintBatchLine
	err := row.Scan(
		&i.ID,
		&i.ComplaintId,
		&i.BatchNumber,
		&i.CreatedAt,
	)
	return i, err
}

const createComplaintPhoto = `-- name: CreateComplaintPhoto :one
INSERT INTO "ComplaintPhoto" (
    id,
    "complaintId",
    filename,
    "originalName",
    mimetype,
    size,
    "storagePath",
    "uploadedById",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW()
)
RETURNING id, "complaintId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
`

type CreateComplaintPhotoParams struct {
	ID           string      `json:"id"`
	ComplaintID  string      `json:"complaint_id"`
	Filename     string      `json:"filename"`
	OriginalName string      `json:"original_name"`
	Mimetype     string      `json:"mimetype"`
	Size         int32       `json:"size"`
	StoragePath  string      `json:"storage_path"`
	UploadedByID pgtype.Text `json:"uploaded_by_id"`
}

func (q *Queries) CreateComplaintPhoto(ctx context.Context, arg CreateComplaintPhotoParams) (ComplaintPhoto, error) {
	row := q.db.QueryRow(ctx, createComplaintPhoto,
		arg.ID,
		arg.ComplaintID,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
		arg.StoragePath,
		arg.UploadedByID,
	)
	var i ComplaintPhoto
	err := row.Scan(
		&i.ID,
		&i.ComplaintId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComplaintBatchLinesByComplaint = `-- name: DeleteComplaintBatchLinesByComplaint :exec
DELETE FROM "ComplaintBatchLine"
WHERE "complaintId" = $1
`

func (q *Queries) DeleteComplaintBatchLinesByComplaint(ctx context.Context, complaintID string) error {
	_, err := q.db.Exec(ctx, deleteComplaintBatchLinesByComplaint, complaintID)
	return err
}

const getComplaintByID = `-- name: GetComplaintByID :one
SELECT "complaintId", "complaintDate", "projectName", "clientName", "siteLocation", "complaintDescription", "rootCauseRemarks", "resolutionStatus", "resolutionDate", "responsibleStage", "createdAt", "updatedAt"
FROM "Complaint"
WHERE "complaintId" = $1
`

func (q *Queries) GetComplaintByID(ctx context.Context, complaintID string) (Complaint, error) {
	row := q.db.QueryRow(ctx, getComplaintByID, complaintID)
	var i Complaint
	err := row.Scan(
		&i.ComplaintId,
		&i.ComplaintDate,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.ComplaintDescription,
		&i.RootCauseRemarks,
		&i.ResolutionStatus,
		&i.ResolutionDate,
		&i.ResponsibleStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplaintPhotoByID = `-- name: GetComplaintPhotoByID :one
SELECT id, "complaintId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "ComplaintPhoto"
WHERE id = $1
`

func (q *Queries) GetComplaintPhotoByID(ctx context.Context, id string) (ComplaintPhoto, error) {
	row := q.db.QueryRow(ctx, getComplaintPhotoByID, id)
	var i ComplaintPhoto
	err := row.Scan(
		&i.ID,
		&i.ComplaintId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestComplaintIDByPrefix = `-- name: GetLatestComplaintIDByPrefix :one
SELECT "complaintId"
FROM "Complaint"
WHERE "complaintId" LIKE $1 || '%'
ORDER BY "complaintId" DESC
LIMIT 1
`

func (q *Queries) GetLatestComplaintIDByPrefix(ctx context.Context, prefix pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getLatestComplaintIDByPrefix, prefix)
	var complaintId string
	err := row.Scan(&complaintId)
	return complaintId, err
}

const listComplaintBatchLinesByComplaint = `-- name: ListComplaintBatchLinesByComplaint :many
SELECT id, "complaintId", "batchNumber", "createdAt"
FROM "ComplaintBatchLine"
WHERE "complaintId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListComplaintBatchLinesByComplaint(ctx context.Context, complaintID string) ([]ComplaintBatchLine, error) {
	rows, err := q.db.Query(ctx, listComplaintBatchLinesByComplaint, complaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplaintBatchLine{}
	for rows.Next() {
		var i ComplaintBatchLine
		if err := rows.Scan(
			&i.ID,
			&i.ComplaintId,
			&i.BatchNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplaintPhotosByComplaintID = `-- name: ListComplaintPhotosByComplaintID :many
SELECT id, "complaintId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "ComplaintPhoto"
WHERE "complaintId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListComplaintPhotosByComplaintID(ctx context.Context, complaintID string) ([]ComplaintPhoto, error) {
	rows, err := q.db.Query(ctx, listComplaintPhotosByComplaintID, complaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplaintPhoto{}
	for rows.Next() {
		var i ComplaintPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ComplaintId,
			&i.Filename,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.StoragePath,
			&i.UploadedById,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComplaint = `-- name: UpdateComplaint :one
UPDATE "Complaint"
SET
    "complaintDate" = COALESCE($1, "complaintDate"),
    "projectName" = COALESCE($2, "projectName"),
    "clientName" = COALESCE($3, "clientName"),
    "siteLocation" = COALESCE($4, "siteLocation"),
    "complaintDescription" = COALESCE($5, "complaintDescription"),
    "rootCauseRemarks" = COALESCE($6, "rootCauseRemarks"),
    "resolutionStatus" = COALESCE($7, "resolutionStatus"),
    "resolutionDate" = COALESCE($8, "resolutionDate"),
    "responsibleStage" = COALESCE($9, "responsibleStage"),
    "updatedAt" = NOW()
WHERE "complaintId" = $10
RETURNING "complaintId", "complaintDate", "projectName", "clientName", "siteLocation", "complaintDescription", "rootCauseRemarks", "resolutionStatus", "resolutionDate", "responsibleStage", "createdAt", "updatedAt"
`

type UpdateComplaintParams struct {
	ComplaintDate        pgtype.Timestamp     `json:"complaint_date"`
	ProjectName          pgtype.Text          `json:"project_name"`
	ClientName           pgtype.Text          `json:"client_name"`
	SiteLocation         pgtype.Text          `json:"site_location"`
	ComplaintDescription pgtype.Text          `json:"complaint_description"`
	RootCauseRemarks     pgtype.Text          `json:"root_cause_remarks"`
	ResolutionStatus     NullResolutionStatus `json:"resolution_status"`
	ResolutionDate       pgtype.Timestamp     `json:"resolution_date"`
	ResponsibleStage     NullResponsibleStage `json:"responsible_stage"`
	ComplaintID          string               `json:"complaint_id"`
}

func (q *Queries) UpdateComplaint(ctx context.Context, arg UpdateComplaintParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, updateComplaint,
		arg.ComplaintDate,
		arg.ProjectName,
		arg.ClientName,
		arg.SiteLocation,
		arg.ComplaintDescription,
		arg.RootCauseRemarks,
		arg.ResolutionStatus,
		arg.ResolutionDate,
		arg.ResponsibleStage,
		arg.ComplaintID,
	)
	var i Complaint
	err := row.Scan(
		&i.ComplaintId,
		&i.ComplaintDate,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.ComplaintDescription,
		&i.RootCauseRemarks,
		&i.ResolutionStatus,
		&i.ResolutionDate,
		&i.ResponsibleStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
