// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsFiltered = `-- name: CountAuditLogsFiltered :one
SELECT COUNT(*)::bigint AS count
FROM "AuditLog" al
WHERE ($1::text IS NULL OR al."entityType" = $1)
  AND ($2::text IS NULL OR al.action = $2)
`

type CountAuditLogsFilteredParams struct {
	EntityType   pgtype.Text `json:"entity_type"`
	ActionFilter pgtype.Text `json:"action_filter"`
}

func (q *Queries) CountAuditLogsFiltered(ctx context.Context, arg CountAuditLogsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsFiltered, arg.EntityType, arg.ActionFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComplaintsWithUndeterminedStage = `-- name: CountComplaintsWithUndeterminedStage :one
SELECT COUNT(*)::bigint AS count
FROM "Complaint"
WHERE "responsibleStage" IS NULL
`

func (q *Queries) CountComplaintsWithUndeterminedStage(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaintsWithUndeterminedStage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingSiteDispatches = `-- name: CountPendingSiteDispatches :one
SELECT COUNT(*)::bigint AS count
FROM "SiteDispatch" sd
WHERE NOT EXISTS (
    SELECT 1 FROM "SiteInstallation" si WHERE si."dispatchNoteNumber" = sd."dispatchNoteNumber"
)
`

func (q *Queries) CountPendingSiteDispatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSiteDispatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSiteDispatches = `-- name: CountRecentSiteDispatches :one
SELECT COUNT(*)::bigint AS count
FROM "SiteDispatch"
WHERE "dispatchDate" >= $1
`

func (q *Queries) CountRecentSiteDispatches(ctx context.Context, sinceDate pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSiteDispatches, sinceDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint AS count
FROM "SystemNotification"
WHERE "isRead" = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const groupComplaintsByResponsibleStage = `-- name: GroupComplaintsByResponsibleStage :many
SELECT "responsibleStage"::text AS responsible_stage, COUNT(*)::bigint AS count
FROM "Complaint"
WHERE "responsibleStage" IS NOT NULL
GROUP BY "responsibleStage"
`

type GroupComplaintsByResponsibleStageRow struct {
	ResponsibleStage string `json:"responsible_stage"`
	Count            int64  `json:"count"`
}

func (q *Queries) GroupComplaintsByResponsibleStage(ctx context.Context) ([]GroupComplaintsByResponsibleStageRow, error) {
	rows, err := q.db.Query(ctx, groupComplaintsByResponsibleStage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupComplaintsByResponsibleStageRow{}
	for rows.Next() {
		var i GroupComplaintsByResponsibleStageRow
		if err := rows.Scan(&i.ResponsibleStage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsWithUser = `-- name: ListAuditLogsWithUser :many
SELECT
    al.id,
    al.action,
    al."entityType",
    al."entityId",
    al."oldValues",
    al."newValues",
    al."createdAt",
    u."fullName",
    u.email,
    r.name AS role_name
FROM "AuditLog" al
INNER JOIN "User" u ON u.id = al."userId"
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE ($1::text IS NULL OR al."entityType" = $1)
  AND ($2::text IS NULL OR al.action = $2)
ORDER BY al."createdAt" DESC
LIMIT $4
OFFSET $3
`

type ListAuditLogsWithUserParams struct {
	EntityType   pgtype.Text `json:"entity_type"`
	ActionFilter pgtype.Text `json:"action_filter"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

type ListAuditLogsWithUserRow struct {
	ID         string           `json:"id"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entityType"`
	EntityId   pgtype.Text      `json:"entityId"`
	OldValues  []byte           `json:"oldValues"`
	NewValues  []byte           `json:"newValues"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	FullName   string           `json:"fullName"`
	Email      string           `json:"email"`
	RoleName   string           `json:"role_name"`
}

func (q *Queries) ListAuditLogsWithUser(ctx context.Context, arg ListAuditLogsWithUserParams) ([]ListAuditLogsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsWithUser,
		arg.EntityType,
		arg.ActionFilter,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsWithUserRow{}
	for rows.Next() {
		var i ListAuditLogsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityId,
			&i.OldValues,
			&i.NewValues,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenComplaintsForDashboard = `-- name: ListOpenComplaintsForDashboard :many
SELECT
    "complaintId",
    "complaintDate",
    "projectName",
    "resolutionStatus"::text AS resolution_status,
    "responsibleStage"::text AS responsible_stage
FROM "Complaint"
WHERE "resolutionStatus" IN ('OPEN', 'UNDER_INVESTIGATION')
ORDER BY "complaintDate" DESC
LIMIT $1
`

type ListOpenComplaintsForDashboardRow struct {
	ComplaintId      string           `json:"complaintId"`
	ComplaintDate    pgtype.Timestamp `json:"complaintDate"`
	ProjectName      string           `json:"projectName"`
	ResolutionStatus string           `json:"resolution_status"`
	ResponsibleStage string           `json:"responsible_stage"`
}

func (q *Queries) ListOpenComplaintsForDashboard(ctx context.Context, resultLimit int32) ([]ListOpenComplaintsForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listOpenComplaintsForDashboard, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenComplaintsForDashboardRow{}
	for rows.Next() {
		var i ListOpenComplaintsForDashboardRow
		if err := rows.Scan(
			&i.ComplaintId,
			&i.ComplaintDate,
			&i.ProjectName,
			&i.ResolutionStatus,
			&i.ResponsibleStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingQcBatchesForDashboard = `-- name: ListPendingQcBatchesForDashboard :many
SELECT
    pb."batchNumber",
    pb."productionOrderNumber",
    pb."productType",
    pb."quantityProduced",
    pb."productionDate"
FROM "ProductionBatch" pb
WHERE NOT EXISTS (
    SELECT 1 FROM "QCInspection" qc WHERE qc."batchNumber" = pb."batchNumber"
)
ORDER BY pb."productionDate" DESC
LIMIT $1
`

type ListPendingQcBatchesForDashboardRow struct {
	BatchNumber           string           `json:"batchNumber"`
	ProductionOrderNumber string           `json:"productionOrderNumber"`
	ProductType           string           `json:"productType"`
	QuantityProduced      pgtype.Numeric   `json:"quantityProduced"`
	ProductionDate        pgtype.Timestamp `json:"productionDate"`
}

func (q *Queries) ListPendingQcBatchesForDashboard(ctx context.Context, resultLimit int32) ([]ListPendingQcBatchesForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listPendingQcBatchesForDashboard, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingQcBatchesForDashboardRow{}
	for rows.Next() {
		var i ListPendingQcBatchesForDashboardRow
		if err := rows.Scan(
			&i.BatchNumber,
			&i.ProductionOrderNumber,
			&i.ProductType,
			&i.QuantityProduced,
			&i.ProductionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionBatchesForFgCalc = `-- name: ListProductionBatchesForFgCalc :many
SELECT "batchNumber", "productType", "quantityProduced"
FROM "ProductionBatch"
`

type ListProductionBatchesForFgCalcRow struct {
	BatchNumber      string         `json:"batchNumber"`
	ProductType      string         `json:"productType"`
	QuantityProduced pgtype.Numeric `json:"quantityProduced"`
}

func (q *Queries) ListProductionBatchesForFgCalc(ctx context.Context) ([]ListProductionBatchesForFgCalcRow, error) {
	rows, err := q.db.Query(ctx, listProductionBatchesForFgCalc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionBatchesForFgCalcRow{}
	for rows.Next() {
		var i ListProductionBatchesForFgCalcRow
		if err := rows.Scan(&i.BatchNumber, &i.ProductType, &i.QuantityProduced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDispatchesForDashboard = `-- name: ListRecentDispatchesForDashboard :many
SELECT
    sd."dispatchNoteNumber",
    sd."dispatchDate",
    sd."projectName",
    sd."clientName",
    sd."siteLocation",
    (
        SELECT COUNT(*)::bigint
        FROM "DispatchBatchLine" dbl
        WHERE dbl."dispatchNoteNumber" = sd."dispatchNoteNumber"
    ) AS batch_count,
    (
        SELECT COALESCE(SUM("quantityDispatched"), 0)::numeric
        FROM "DispatchBatchLine" dbl
        WHERE dbl."dispatchNoteNumber" = sd."dispatchNoteNumber"
    ) AS total_quantity,
    EXISTS (
        SELECT 1 FROM "SiteInstallation" si
        WHERE si."dispatchNoteNumber" = sd."dispatchNoteNumber"
    ) AS site_installed
FROM "SiteDispatch" sd
ORDER BY sd."dispatchDate" DESC
LIMIT $1
`

type ListRecentDispatchesForDashboardRow struct {
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	DispatchDate       pgtype.Timestamp `json:"dispatchDate"`
	ProjectName        string           `json:"projectName"`
	ClientName         string           `json:"clientName"`
	SiteLocation       string           `json:"siteLocation"`
	BatchCount         int64            `json:"batch_count"`
	TotalQuantity      pgtype.Numeric   `json:"total_quantity"`
	SiteInstalled      bool             `json:"site_installed"`
}

func (q *Queries) ListRecentDispatchesForDashboard(ctx context.Context, resultLimit int32) ([]ListRecentDispatchesForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listRecentDispatchesForDashboard, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDispatchesForDashboardRow{}
	for rows.Next() {
		var i ListRecentDispatchesForDashboardRow
		if err := rows.Scan(
			&i.DispatchNoteNumber,
			&i.DispatchDate,
			&i.ProjectName,
			&i.ClientName,
			&i.SiteLocation,
			&i.BatchCount,
			&i.TotalQuantity,
			&i.SiteInstalled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemNotifications = `-- name: ListSystemNotifications :many
SELECT id, type, title, message, "entityType", "entityId", "isRead", "createdAt"
FROM "SystemNotification"
WHERE ($1::bool = false OR "isRead" = false)
ORDER BY "createdAt" DESC
LIMIT $2
`

type ListSystemNotificationsParams struct {
	UnreadOnly  bool  `json:"unread_only"`
	ResultLimit int32 `json:"result_limit"`
}

func (q *Queries) ListSystemNotifications(ctx context.Context, arg ListSystemNotificationsParams) ([]SystemNotification, error) {
	rows, err := q.db.Query(ctx, listSystemNotifications, arg.UnreadOnly, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemNotification{}
	for rows.Next() {
		var i SystemNotification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.EntityType,
			&i.EntityId,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE "SystemNotification"
SET "isRead" = true
WHERE "isRead" = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead)
	return err
}

const markNotificationReadByID = `-- name: MarkNotificationReadByID :exec
UPDATE "SystemNotification"
SET "isRead" = true
WHERE id = $1
`

func (q *Queries) MarkNotificationReadByID(ctx context.Context, notificationID string) error {
	_, err := q.db.Exec(ctx, markNotificationReadByID, notificationID)
	return err
}

const markNotificationsReadByIDs = `-- name: MarkNotificationsReadByIDs :exec
UPDATE "SystemNotification"
SET "isRead" = true
WHERE id = ANY($1::text[])
`

func (q *Queries) MarkNotificationsReadByIDs(ctx context.Context, notificationIds []string) error {
	_, err := q.db.Exec(ctx, markNotificationsReadByIDs, notificationIds)
	return err
}
