// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistinctDispatchProjects = `-- name: CountDistinctDispatchProjects :one
SELECT COUNT(DISTINCT "projectName")::bigint AS count FROM "SiteDispatch"
`

func (q *Queries) CountDistinctDispatchProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctDispatchProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteDispatches = `-- name: CountSiteDispatches :one
SELECT COUNT(*)::bigint AS count FROM "SiteDispatch"
`

func (q *Queries) CountSiteDispatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSiteDispatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDispatchBatchLine = `-- name: CreateDispatchBatchLine :one
INSERT INTO "DispatchBatchLine" (
    id,
    "dispatchNoteNumber",
    "batchNumber",
    "quantityDispatched",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING id, "dispatchNoteNumber", "batchNumber", "quantityDispatched", "createdAt"
`

type CreateDispatchBatchLineParams struct {
	ID                 string         `json:"id"`
	DispatchNoteNumber string         `json:"dispatch_note_number"`
	BatchNumber        string         `json:"batch_number"`
	QuantityDispatched pgtype.Numeric `json:"quantity_dispatched"`
}

func (q *Queries) CreateDispatchBatchLine(ctx context.Context, arg CreateDispatchBatchLineParams) (DispatchBatchLine, error) {
	row := q.db.QueryRow(ctx, createDispatchBatchLine,
		arg.ID,
		arg.DispatchNoteNumber,
		arg.BatchNumber,
		arg.QuantityDispatched,
	)
	var i DispatchBatchLine
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.BatchNumber,
		&i.QuantityDispatched,
		&i.CreatedAt,
	)
	return i, err
}

const createSiteDispatch = `-- name: CreateSiteDispatch :one
INSERT INTO "SiteDispatch" (
    "dispatchNoteNumber",
    "dispatchDate",
    "vehicleNumber",
    "transporterName",
    "projectName",
    "clientName",
    "siteLocation",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW(),
    NOW()
)
RETURNING "dispatchNoteNumber", "dispatchDate", "vehicleNumber", "transporterName", "projectName", "clientName", "siteLocation", "createdAt", "updatedAt"
`

type CreateSiteDispatchParams struct {
	DispatchNoteNumber string           `json:"dispatch_note_number"`
	DispatchDate       pgtype.Timestamp `json:"dispatch_date"`
	VehicleNumber      pgtype.Text      `json:"vehicle_number"`
	TransporterName    pgtype.Text      `json:"transporter_name"`
	ProjectName        string           `json:"project_name"`
	ClientName         string           `json:"client_name"`
	SiteLocation       string           `json:"site_location"`
}

func (q *Queries) CreateSiteDispatch(ctx context.Context, arg CreateSiteDispatchParams) (SiteDispatch, error) {
	row := q.db.QueryRow(ctx, createSiteDispatch,
		arg.DispatchNoteNumber,
		arg.DispatchDate,
		arg.VehicleNumber,
		arg.TransporterName,
		arg.ProjectName,
		arg.ClientName,
		arg.SiteLocation,
	)
	var i SiteDispatch
	err := row.Scan(
		&i.DispatchNoteNumber,
		&i.DispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDispatchBatchLinesByNote = `-- name: DeleteDispatchBatchLinesByNote :exec
DELETE FROM "DispatchBatchLine"
WHERE "dispatchNoteNumber" = $1
`

func (q *Queries) DeleteDispatchBatchLinesByNote(ctx context.Context, dispatchNoteNumber string) error {
	_, err := q.db.Exec(ctx, deleteDispatchBatchLinesByNote, dispatchNoteNumber)
	return err
}

const getLatestDispatchNoteByPrefix = `-- name: GetLatestDispatchNoteByPrefix :one
SELECT "dispatchNoteNumber"
FROM "SiteDispatch"
WHERE "dispatchNoteNumber" LIKE $1 || '%'
ORDER BY "dispatchNoteNumber" DESC
LIMIT 1
`

func (q *Queries) GetLatestDispatchNoteByPrefix(ctx context.Context, prefix pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getLatestDispatchNoteByPrefix, prefix)
	var dispatchNoteNumber string
	err := row.Scan(&dispatchNoteNumber)
	return dispatchNoteNumber, err
}

const getSiteDispatchByNoteNumber = `-- name: GetSiteDispatchByNoteNumber :one
SELECT "dispatchNoteNumber", "dispatchDate", "vehicleNumber", "transporterName", "projectName", "clientName", "siteLocation", "createdAt", "updatedAt"
FROM "SiteDispatch"
WHERE "dispatchNoteNumber" = $1
`

func (q *Queries) GetSiteDispatchByNoteNumber(ctx context.Context, dispatchNoteNumber string) (SiteDispatch, error) {
	row := q.db.QueryRow(ctx, getSiteDispatchByNoteNumber, dispatchNoteNumber)
	var i SiteDispatch
	err := row.Scan(
		&i.DispatchNoteNumber,
		&i.DispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteInstallationSummaryByDispatchNote = `-- name: GetSiteInstallationSummaryByDispatchNote :one
SELECT
    si.id,
    si."dispatchNoteNumber",
    si."siteReceiptDate",
    si."installationDate",
    si."installerEpcPartner",
    si."quantityInstalled",
    si."createdAt",
    si."updatedAt",
    (
        SELECT COUNT(*)::bigint
        FROM "SiteInstallationPhoto" sip
        WHERE sip."installationId" = si.id
    ) AS photo_count
FROM "SiteInstallation" si
WHERE si."dispatchNoteNumber" = $1
`

type GetSiteInstallationSummaryByDispatchNoteRow struct {
	ID                  string           `json:"id"`
	DispatchNoteNumber  string           `json:"dispatchNoteNumber"`
	SiteReceiptDate     pgtype.Timestamp `json:"siteReceiptDate"`
	InstallationDate    pgtype.Timestamp `json:"installationDate"`
	InstallerEpcPartner string           `json:"installerEpcPartner"`
	QuantityInstalled   pgtype.Numeric   `json:"quantityInstalled"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	UpdatedAt           pgtype.Timestamp `json:"updatedAt"`
	PhotoCount          int64            `json:"photo_count"`
}

func (q *Queries) GetSiteInstallationSummaryByDispatchNote(ctx context.Context, dispatchNoteNumber string) (GetSiteInstallationSummaryByDispatchNoteRow, error) {
	row := q.db.QueryRow(ctx, getSiteInstallationSummaryByDispatchNote, dispatchNoteNumber)
	var i GetSiteInstallationSummaryByDispatchNoteRow
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.SiteReceiptDate,
		&i.InstallationDate,
		&i.InstallerEpcPartner,
		&i.QuantityInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoCount,
	)
	return i, err
}

const listDispatchBatchLinesByNote = `-- name: ListDispatchBatchLinesByNote :many
SELECT id, "dispatchNoteNumber", "batchNumber", "quantityDispatched", "createdAt"
FROM "DispatchBatchLine"
WHERE "dispatchNoteNumber" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListDispatchBatchLinesByNote(ctx context.Context, dispatchNoteNumber string) ([]DispatchBatchLine, error) {
	rows, err := q.db.Query(ctx, listDispatchBatchLinesByNote, dispatchNoteNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchBatchLine{}
	for rows.Next() {
		var i DispatchBatchLine
		if err := rows.Scan(
			&i.ID,
			&i.DispatchNoteNumber,
			&i.BatchNumber,
			&i.QuantityDispatched,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siteDispatchExists = `-- name: SiteDispatchExists :one
SELECT EXISTS(
    SELECT 1 FROM "SiteDispatch" WHERE "dispatchNoteNumber" = $1
) AS exists
`

func (q *Queries) SiteDispatchExists(ctx context.Context, dispatchNoteNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, siteDispatchExists, dispatchNoteNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sumAllDispatchedQuantity = `-- name: SumAllDispatchedQuantity :one
SELECT COALESCE(SUM("quantityDispatched"), 0)::numeric AS total
FROM "DispatchBatchLine"
`

func (q *Queries) SumAllDispatchedQuantity(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAllDispatchedQuantity)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumBatchDispatchedQuantityExcludingNote = `-- name: SumBatchDispatchedQuantityExcludingNote :one
SELECT COALESCE(SUM("quantityDispatched"), 0)::numeric AS total
FROM "DispatchBatchLine"
WHERE "batchNumber" = $1
  AND "dispatchNoteNumber" <> $2
`

type SumBatchDispatchedQuantityExcludingNoteParams struct {
	BatchNumber               string `json:"batch_number"`
	ExcludeDispatchNoteNumber string `json:"exclude_dispatch_note_number"`
}

func (q *Queries) SumBatchDispatchedQuantityExcludingNote(ctx context.Context, arg SumBatchDispatchedQuantityExcludingNoteParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumBatchDispatchedQuantityExcludingNote, arg.BatchNumber, arg.ExcludeDispatchNoteNumber)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumDispatchNoteQuantity = `-- name: SumDispatchNoteQuantity :one
SELECT COALESCE(SUM("quantityDispatched"), 0)::numeric AS total
FROM "DispatchBatchLine"
WHERE "dispatchNoteNumber" = $1
`

func (q *Queries) SumDispatchNoteQuantity(ctx context.Context, dispatchNoteNumber string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumDispatchNoteQuantity, dispatchNoteNumber)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateSiteDispatch = `-- name: UpdateSiteDispatch :one
UPDATE "SiteDispatch"
SET
    "dispatchDate" = COALESCE($1, "dispatchDate"),
    "vehicleNumber" = COALESCE($2, "vehicleNumber"),
    "transporterName" = COALESCE($3, "transporterName"),
    "projectName" = COALESCE($4, "projectName"),
    "clientName" = COALESCE($5, "clientName"),
    "siteLocation" = COALESCE($6, "siteLocation"),
    "updatedAt" = NOW()
WHERE "dispatchNoteNumber" = $7
RETURNING "dispatchNoteNumber", "dispatchDate", "vehicleNumber", "transporterName", "projectName", "clientName", "siteLocation", "createdAt", "updatedAt"
`

type UpdateSiteDispatchParams struct {
	DispatchDate       pgtype.Timestamp `json:"dispatch_date"`
	VehicleNumber      pgtype.Text      `json:"vehicle_number"`
	TransporterName    pgtype.Text      `json:"transporter_name"`
	ProjectName        pgtype.Text      `json:"project_name"`
	ClientName         pgtype.Text      `json:"client_name"`
	SiteLocation       pgtype.Text      `json:"site_location"`
	DispatchNoteNumber string           `json:"dispatch_note_number"`
}

func (q *Queries) UpdateSiteDispatch(ctx context.Context, arg UpdateSiteDispatchParams) (SiteDispatch, error) {
	row := q.db.QueryRow(ctx, updateSiteDispatch,
		arg.DispatchDate,
		arg.VehicleNumber,
		arg.TransporterName,
		arg.ProjectName,
		arg.ClientName,
		arg.SiteLocation,
		arg.DispatchNoteNumber,
	)
	var i SiteDispatch
	err := row.Scan(
		&i.DispatchNoteNumber,
		&i.DispatchDate,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.ProjectName,
		&i.ClientName,
		&i.SiteLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
