// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents_hub.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAllCoilDocumentsForHub = `-- name: ListAllCoilDocumentsForHub :many
SELECT
    d.id,
    d."coilNumber",
    d."documentType"::text AS document_type,
    d."originalName",
    d.mimetype,
    d.size,
    d."createdAt"
FROM "CoilDocument" d
ORDER BY d."createdAt" DESC
`

type ListAllCoilDocumentsForHubRow struct {
	ID           string           `json:"id"`
	CoilNumber   string           `json:"coilNumber"`
	DocumentType string           `json:"document_type"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAllCoilDocumentsForHub(ctx context.Context) ([]ListAllCoilDocumentsForHubRow, error) {
	rows, err := q.db.Query(ctx, listAllCoilDocumentsForHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCoilDocumentsForHubRow{}
	for rows.Next() {
		var i ListAllCoilDocumentsForHubRow
		if err := rows.Scan(
			&i.ID,
			&i.CoilNumber,
			&i.DocumentType,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllComplaintPhotosForHub = `-- name: ListAllComplaintPhotosForHub :many
SELECT
    p.id,
    p."originalName",
    p.mimetype,
    p.size,
    p."createdAt",
    c."complaintId",
    c."projectName"
FROM "ComplaintPhoto" p
INNER JOIN "Complaint" c ON c."complaintId" = p."complaintId"
ORDER BY p."createdAt" DESC
`

type ListAllComplaintPhotosForHubRow struct {
	ID           string           `json:"id"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	ComplaintId  string           `json:"complaintId"`
	ProjectName  string           `json:"projectName"`
}

func (q *Queries) ListAllComplaintPhotosForHub(ctx context.Context) ([]ListAllComplaintPhotosForHubRow, error) {
	rows, err := q.db.Query(ctx, listAllComplaintPhotosForHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllComplaintPhotosForHubRow{}
	for rows.Next() {
		var i ListAllComplaintPhotosForHubRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
			&i.ComplaintId,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllQcPhotosForHub = `-- name: ListAllQcPhotosForHub :many
SELECT
    p.id,
    p."originalName",
    p.mimetype,
    p.size,
    p."createdAt",
    qc."batchNumber"
FROM "QCInspectionPhoto" p
INNER JOIN "QCInspection" qc ON qc.id = p."inspectionId"
ORDER BY p."createdAt" DESC
`

type ListAllQcPhotosForHubRow struct {
	ID           string           `json:"id"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	BatchNumber  string           `json:"batchNumber"`
}

func (q *Queries) ListAllQcPhotosForHub(ctx context.Context) ([]ListAllQcPhotosForHubRow, error) {
	rows, err := q.db.Query(ctx, listAllQcPhotosForHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllQcPhotosForHubRow{}
	for rows.Next() {
		var i ListAllQcPhotosForHubRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
			&i.BatchNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSiteInstallationPhotosForHub = `-- name: ListAllSiteInstallationPhotosForHub :many
SELECT
    p.id,
    p."originalName",
    p.mimetype,
    p.size,
    p."createdAt",
    si."dispatchNoteNumber",
    sd."projectName"
FROM "SiteInstallationPhoto" p
INNER JOIN "SiteInstallation" si ON si.id = p."installationId"
INNER JOIN "SiteDispatch" sd ON sd."dispatchNoteNumber" = si."dispatchNoteNumber"
ORDER BY p."createdAt" DESC
`

type ListAllSiteInstallationPhotosForHubRow struct {
	ID                 string           `json:"id"`
	OriginalName       string           `json:"originalName"`
	Mimetype           string           `json:"mimetype"`
	Size               int32            `json:"size"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	ProjectName        string           `json:"projectName"`
}

func (q *Queries) ListAllSiteInstallationPhotosForHub(ctx context.Context) ([]ListAllSiteInstallationPhotosForHubRow, error) {
	rows, err := q.db.Query(ctx, listAllSiteInstallationPhotosForHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSiteInstallationPhotosForHubRow{}
	for rows.Next() {
		var i ListAllSiteInstallationPhotosForHubRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
			&i.DispatchNoteNumber,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSunrackReceiptPhotosForHub = `-- name: ListAllSunrackReceiptPhotosForHub :many
SELECT
    p.id,
    p."originalName",
    p.mimetype,
    p.size,
    p."createdAt",
    r."slitCoilId",
    sr."parentCoilNumber"
FROM "SunrackReceiptPhoto" p
INNER JOIN "SunrackReceipt" r ON r.id = p."receiptId"
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = r."slitCoilId"
ORDER BY p."createdAt" DESC
`

type ListAllSunrackReceiptPhotosForHubRow struct {
	ID               string           `json:"id"`
	OriginalName     string           `json:"originalName"`
	Mimetype         string           `json:"mimetype"`
	Size             int32            `json:"size"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	SlitCoilId       string           `json:"slitCoilId"`
	ParentCoilNumber string           `json:"parentCoilNumber"`
}

func (q *Queries) ListAllSunrackReceiptPhotosForHub(ctx context.Context) ([]ListAllSunrackReceiptPhotosForHubRow, error) {
	rows, err := q.db.Query(ctx, listAllSunrackReceiptPhotosForHub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSunrackReceiptPhotosForHubRow{}
	for rows.Next() {
		var i ListAllSunrackReceiptPhotosForHubRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
			&i.SlitCoilId,
			&i.ParentCoilNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
