// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finished_goods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sumBatchDispatchedQuantity = `-- name: SumBatchDispatchedQuantity :one
SELECT COALESCE(SUM("quantityDispatched"), 0)::numeric AS total
FROM "DispatchBatchLine"
WHERE "batchNumber" = $1
`

func (q *Queries) SumBatchDispatchedQuantity(ctx context.Context, batchNumber string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumBatchDispatchedQuantity, batchNumber)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
