// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoilDocumentType string

const (
	CoilDocumentTypeMTC     CoilDocumentType = "MTC"
	CoilDocumentTypeINVOICE CoilDocumentType = "INVOICE"
	CoilDocumentTypeOTHER   CoilDocumentType = "OTHER"
)

func (e *CoilDocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoilDocumentType(s)
	case string:
		*e = CoilDocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoilDocumentType: %T", src)
	}
	return nil
}

type NullCoilDocumentType struct {
	CoilDocumentType CoilDocumentType `json:"CoilDocumentType"`
	Valid            bool             `json:"valid"` // Valid is true if CoilDocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoilDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.CoilDocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoilDocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoilDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoilDocumentType), nil
}

type CoilStatus string

const (
	CoilStatusACTIVE   CoilStatus = "ACTIVE"
	CoilStatusARCHIVED CoilStatus = "ARCHIVED"
)

func (e *CoilStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoilStatus(s)
	case string:
		*e = CoilStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoilStatus: %T", src)
	}
	return nil
}

type NullCoilStatus struct {
	CoilStatus CoilStatus `json:"CoilStatus"`
	Valid      bool       `json:"valid"` // Valid is true if CoilStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoilStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoilStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoilStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoilStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoilStatus), nil
}

type InspectionResult string

const (
	InspectionResultPENDING     InspectionResult = "PENDING"
	InspectionResultPASS        InspectionResult = "PASS"
	InspectionResultCONDITIONAL InspectionResult = "CONDITIONAL"
	InspectionResultFAIL        InspectionResult = "FAIL"
)

func (e *InspectionResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InspectionResult(s)
	case string:
		*e = InspectionResult(s)
	default:
		return fmt.Errorf("unsupported scan type for InspectionResult: %T", src)
	}
	return nil
}

type NullInspectionResult struct {
	InspectionResult InspectionResult `json:"InspectionResult"`
	Valid            bool             `json:"valid"` // Valid is true if InspectionResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInspectionResult) Scan(value interface{}) error {
	if value == nil {
		ns.InspectionResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InspectionResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInspectionResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InspectionResult), nil
}

type ModuleAccess string

const (
	ModuleAccessNONE  ModuleAccess = "NONE"
	ModuleAccessREAD  ModuleAccess = "READ"
	ModuleAccessWRITE ModuleAccess = "WRITE"
	ModuleAccessFULL  ModuleAccess = "FULL"
)

func (e *ModuleAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModuleAccess(s)
	case string:
		*e = ModuleAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for ModuleAccess: %T", src)
	}
	return nil
}

type NullModuleAccess struct {
	ModuleAccess ModuleAccess `json:"ModuleAccess"`
	Valid        bool         `json:"valid"` // Valid is true if ModuleAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModuleAccess) Scan(value interface{}) error {
	if value == nil {
		ns.ModuleAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModuleAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModuleAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModuleAccess), nil
}

type NotificationType string

const (
	NotificationTypeCOMPLAINTCREATED NotificationType = "COMPLAINT_CREATED"
	NotificationTypeQCFAILED         NotificationType = "QC_FAILED"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"NotificationType"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type QcResult string

const (
	QcResultPASS   QcResult = "PASS"
	QcResultFAIL   QcResult = "FAIL"
	QcResultREWORK QcResult = "REWORK"
)

func (e *QcResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QcResult(s)
	case string:
		*e = QcResult(s)
	default:
		return fmt.Errorf("unsupported scan type for QcResult: %T", src)
	}
	return nil
}

type NullQcResult struct {
	QcResult QcResult `json:"QcResult"`
	Valid    bool     `json:"valid"` // Valid is true if QcResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQcResult) Scan(value interface{}) error {
	if value == nil {
		ns.QcResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QcResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQcResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QcResult), nil
}

type ResolutionStatus string

const (
	ResolutionStatusOPEN               ResolutionStatus = "OPEN"
	ResolutionStatusUNDERINVESTIGATION ResolutionStatus = "UNDER_INVESTIGATION"
	ResolutionStatusCLOSED             ResolutionStatus = "CLOSED"
)

func (e *ResolutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResolutionStatus(s)
	case string:
		*e = ResolutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResolutionStatus: %T", src)
	}
	return nil
}

type NullResolutionStatus struct {
	ResolutionStatus ResolutionStatus `json:"ResolutionStatus"`
	Valid            bool             `json:"valid"` // Valid is true if ResolutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResolutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResolutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResolutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResolutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResolutionStatus), nil
}

type ResponsibleStage string

const (
	ResponsibleStageAMNS              ResponsibleStage = "AMNS"
	ResponsibleStageSLITTER           ResponsibleStage = "SLITTER"
	ResponsibleStageSUNRACKPRODUCTION ResponsibleStage = "SUNRACK_PRODUCTION"
	ResponsibleStageTRANSPORT         ResponsibleStage = "TRANSPORT"
	ResponsibleStageSITEHANDLING      ResponsibleStage = "SITE_HANDLING"
)

func (e *ResponsibleStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResponsibleStage(s)
	case string:
		*e = ResponsibleStage(s)
	default:
		return fmt.Errorf("unsupported scan type for ResponsibleStage: %T", src)
	}
	return nil
}

type NullResponsibleStage struct {
	ResponsibleStage ResponsibleStage `json:"ResponsibleStage"`
	Valid            bool             `json:"valid"` // Valid is true if ResponsibleStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResponsibleStage) Scan(value interface{}) error {
	if value == nil {
		ns.ResponsibleStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResponsibleStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResponsibleStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResponsibleStage), nil
}

type AuditLog struct {
	ID         string           `json:"id"`
	UserId     string           `json:"userId"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entityType"`
	EntityId   pgtype.Text      `json:"entityId"`
	OldValues  []byte           `json:"oldValues"`
	NewValues  []byte           `json:"newValues"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

type BatchSlitCoilMap struct {
	ID               string           `json:"id"`
	BatchNumber      string           `json:"batchNumber"`
	SlitCoilId       string           `json:"slitCoilId"`
	QuantityConsumed pgtype.Numeric   `json:"quantityConsumed"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
}

type Coil struct {
	CoilNumber                string           `json:"coilNumber"`
	Grade                     string           `json:"grade"`
	Coating                   string           `json:"coating"`
	Size                      string           `json:"size"`
	Weight                    pgtype.Numeric   `json:"weight"`
	Supplier                  string           `json:"supplier"`
	MtcNumber                 pgtype.Text      `json:"mtcNumber"`
	InvoiceNumber             pgtype.Text      `json:"invoiceNumber"`
	AmnsDispatchDate          pgtype.Timestamp `json:"amnsDispatchDate"`
	VehicleNumber             pgtype.Text      `json:"vehicleNumber"`
	TransporterName           pgtype.Text      `json:"transporterName"`
	ReceiptDateSlitter        pgtype.Timestamp `json:"receiptDateSlitter"`
	ReceivingConditionRemarks pgtype.Text      `json:"receivingConditionRemarks"`
	Status                    CoilStatus       `json:"status"`
	ArchivedAt                pgtype.Timestamp `json:"archivedAt"`
	ArchivedById              pgtype.Text      `json:"archivedById"`
	CreatedAt                 pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamp `json:"updatedAt"`
}

type CoilDocument struct {
	ID           string           `json:"id"`
	CoilNumber   string           `json:"coilNumber"`
	DocumentType CoilDocumentType `json:"documentType"`
	Filename     string           `json:"filename"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	StoragePath  string           `json:"storagePath"`
	UploadedById pgtype.Text      `json:"uploadedById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type Complaint struct {
	ComplaintId          string               `json:"complaintId"`
	ComplaintDate        pgtype.Timestamp     `json:"complaintDate"`
	ProjectName          string               `json:"projectName"`
	ClientName           string               `json:"clientName"`
	SiteLocation         string               `json:"siteLocation"`
	ComplaintDescription string               `json:"complaintDescription"`
	RootCauseRemarks     pgtype.Text          `json:"rootCauseRemarks"`
	ResolutionStatus     ResolutionStatus     `json:"resolutionStatus"`
	ResolutionDate       pgtype.Timestamp     `json:"resolutionDate"`
	ResponsibleStage     NullResponsibleStage `json:"responsibleStage"`
	CreatedAt            pgtype.Timestamp     `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp     `json:"updatedAt"`
}

type ComplaintBatchLine struct {
	ID          string           `json:"id"`
	ComplaintId string           `json:"complaintId"`
	BatchNumber string           `json:"batchNumber"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type ComplaintPhoto struct {
	ID           string           `json:"id"`
	ComplaintId  string           `json:"complaintId"`
	Filename     string           `json:"filename"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	StoragePath  string           `json:"storagePath"`
	UploadedById pgtype.Text      `json:"uploadedById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type DispatchBatchLine struct {
	ID                 string           `json:"id"`
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	BatchNumber        string           `json:"batchNumber"`
	QuantityDispatched pgtype.Numeric   `json:"quantityDispatched"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

type ProductionBatch struct {
	BatchNumber           string           `json:"batchNumber"`
	ProductionOrderNumber string           `json:"productionOrderNumber"`
	ProductType           string           `json:"productType"`
	QuantityProduced      pgtype.Numeric   `json:"quantityProduced"`
	ProductionDate        pgtype.Timestamp `json:"productionDate"`
	OperatorShift         string           `json:"operatorShift"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type QCInspection struct {
	ID             string           `json:"id"`
	BatchNumber    string           `json:"batchNumber"`
	QcResult       QcResult         `json:"qcResult"`
	InspectorName  string           `json:"inspectorName"`
	InspectionDate pgtype.Timestamp `json:"inspectionDate"`
	QcRemarks      pgtype.Text      `json:"qcRemarks"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type QCInspectionPhoto struct {
	ID           string           `json:"id"`
	InspectionId string           `json:"inspectionId"`
	Filename     string           `json:"filename"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	StoragePath  string           `json:"storagePath"`
	UploadedById pgtype.Text      `json:"uploadedById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type Role struct {
	ID          string           `json:"id"`
	Code        string           `json:"code"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type RoleModulePermission struct {
	ID     string       `json:"id"`
	RoleId string       `json:"roleId"`
	Module string       `json:"module"`
	Access ModuleAccess `json:"access"`
}

type SiteDispatch struct {
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	DispatchDate       pgtype.Timestamp `json:"dispatchDate"`
	VehicleNumber      pgtype.Text      `json:"vehicleNumber"`
	TransporterName    pgtype.Text      `json:"transporterName"`
	ProjectName        string           `json:"projectName"`
	ClientName         string           `json:"clientName"`
	SiteLocation       string           `json:"siteLocation"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UpdatedAt          pgtype.Timestamp `json:"updatedAt"`
}

type SiteInstallation struct {
	ID                  string           `json:"id"`
	DispatchNoteNumber  string           `json:"dispatchNoteNumber"`
	SiteReceiptDate     pgtype.Timestamp `json:"siteReceiptDate"`
	InstallationDate    pgtype.Timestamp `json:"installationDate"`
	InstallerEpcPartner string           `json:"installerEpcPartner"`
	QuantityInstalled   pgtype.Numeric   `json:"quantityInstalled"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	UpdatedAt           pgtype.Timestamp `json:"updatedAt"`
}

type SiteInstallationPhoto struct {
	ID             string           `json:"id"`
	InstallationId string           `json:"installationId"`
	Filename       string           `json:"filename"`
	OriginalName   string           `json:"originalName"`
	Mimetype       string           `json:"mimetype"`
	Size           int32            `json:"size"`
	StoragePath    string           `json:"storagePath"`
	UploadedById   pgtype.Text      `json:"uploadedById"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
}

type SlittingRecord struct {
	SlitCoilId       string           `json:"slitCoilId"`
	ParentCoilNumber string           `json:"parentCoilNumber"`
	SlitWidthSize    string           `json:"slitWidthSize"`
	SlittingDate     pgtype.Timestamp `json:"slittingDate"`
	SlitCoilWeight   pgtype.Numeric   `json:"slitCoilWeight"`
	SlitterLocation  string           `json:"slitterLocation"`
	DispatchNote     pgtype.Text      `json:"dispatchNote"`
	VehicleNumber    pgtype.Text      `json:"vehicleNumber"`
	TransporterName  pgtype.Text      `json:"transporterName"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
}

type SunrackReceipt struct {
	ID                    string           `json:"id"`
	SlitCoilId            string           `json:"slitCoilId"`
	ReceiptDateSunrack    pgtype.Timestamp `json:"receiptDateSunrack"`
	StorageLocationBin    string           `json:"storageLocationBin"`
	InspectionResult      InspectionResult `json:"inspectionResult"`
	InspectionRemarks     pgtype.Text      `json:"inspectionRemarks"`
	ConfirmedDispatchNote pgtype.Text      `json:"confirmedDispatchNote"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type SunrackReceiptPhoto struct {
	ID           string           `json:"id"`
	ReceiptId    string           `json:"receiptId"`
	Filename     string           `json:"filename"`
	OriginalName string           `json:"originalName"`
	Mimetype     string           `json:"mimetype"`
	Size         int32            `json:"size"`
	StoragePath  string           `json:"storagePath"`
	UploadedById pgtype.Text      `json:"uploadedById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type SystemNotification struct {
	ID         string           `json:"id"`
	Type       NotificationType `json:"type"`
	Title      string           `json:"title"`
	Message    string           `json:"message"`
	EntityType pgtype.Text      `json:"entityType"`
	EntityId   pgtype.Text      `json:"entityId"`
	IsRead     bool             `json:"isRead"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	ID           string           `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"passwordHash"`
	FullName     string           `json:"fullName"`
	IsActive     bool             `json:"isActive"`
	RoleId       string           `json:"roleId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}
