// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemNotification = `-- name: CreateSystemNotification :one
INSERT INTO "SystemNotification" (
    id,
    type,
    title,
    message,
    "entityType",
    "entityId",
    "isRead",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    false,
    NOW()
)
RETURNING id
`

type CreateSystemNotificationParams struct {
	ID               string           `json:"id"`
	NotificationType NotificationType `json:"notification_type"`
	Title            string           `json:"title"`
	Message          string           `json:"message"`
	EntityType       pgtype.Text      `json:"entity_type"`
	EntityID         pgtype.Text      `json:"entity_id"`
}

func (q *Queries) CreateSystemNotification(ctx context.Context, arg CreateSystemNotificationParams) (string, error) {
	row := q.db.QueryRow(ctx, createSystemNotification,
		arg.ID,
		arg.NotificationType,
		arg.Title,
		arg.Message,
		arg.EntityType,
		arg.EntityID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
