// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBatchSlitCoilConsumption = `-- name: AddBatchSlitCoilConsumption :one
UPDATE "BatchSlitCoilMap"
SET "quantityConsumed" = "quantityConsumed" + $1
WHERE id = $2
RETURNING id, "batchNumber", "slitCoilId", "quantityConsumed", "createdAt"
`

type AddBatchSlitCoilConsumptionParams struct {
	AddQuantity pgtype.Numeric `json:"add_quantity"`
	ID          string         `json:"id"`
}

func (q *Queries) AddBatchSlitCoilConsumption(ctx context.Context, arg AddBatchSlitCoilConsumptionParams) (BatchSlitCoilMap, error) {
	row := q.db.QueryRow(ctx, addBatchSlitCoilConsumption, arg.AddQuantity, arg.ID)
	var i BatchSlitCoilMap
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.SlitCoilId,
		&i.QuantityConsumed,
		&i.CreatedAt,
	)
	return i, err
}

const countProductionBatches = `-- name: CountProductionBatches :one
SELECT COUNT(*)::bigint AS count FROM "ProductionBatch"
`

func (q *Queries) CountProductionBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductionBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSlitCoilsWithNonFailReceipt = `-- name: CountSlitCoilsWithNonFailReceipt :one
SELECT COUNT(*)::bigint AS count
FROM "SlittingRecord" sr
INNER JOIN "SunrackReceipt" srr ON srr."slitCoilId" = sr."slitCoilId"
WHERE srr."inspectionResult" != 'FAIL'
`

func (q *Queries) CountSlitCoilsWithNonFailReceipt(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSlitCoilsWithNonFailReceipt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatchSlitCoilMap = `-- name: CreateBatchSlitCoilMap :one
INSERT INTO "BatchSlitCoilMap" (
    id,
    "batchNumber",
    "slitCoilId",
    "quantityConsumed",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING id, "batchNumber", "slitCoilId", "quantityConsumed", "createdAt"
`

type CreateBatchSlitCoilMapParams struct {
	ID               string         `json:"id"`
	BatchNumber      string         `json:"batch_number"`
	SlitCoilID       string         `json:"slit_coil_id"`
	QuantityConsumed pgtype.Numeric `json:"quantity_consumed"`
}

func (q *Queries) CreateBatchSlitCoilMap(ctx context.Context, arg CreateBatchSlitCoilMapParams) (BatchSlitCoilMap, error) {
	row := q.db.QueryRow(ctx, createBatchSlitCoilMap,
		arg.ID,
		arg.BatchNumber,
		arg.SlitCoilID,
		arg.QuantityConsumed,
	)
	var i BatchSlitCoilMap
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.SlitCoilId,
		&i.QuantityConsumed,
		&i.CreatedAt,
	)
	return i, err
}

const createProductionBatch = `-- name: CreateProductionBatch :one
INSERT INTO "ProductionBatch" (
    "batchNumber",
    "productionOrderNumber",
    "productType",
    "quantityProduced",
    "productionDate",
    "operatorShift",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING "batchNumber", "productionOrderNumber", "productType", "quantityProduced", "productionDate", "operatorShift", "createdAt", "updatedAt"
`

type CreateProductionBatchParams struct {
	BatchNumber           string           `json:"batch_number"`
	ProductionOrderNumber string           `json:"production_order_number"`
	ProductType           string           `json:"product_type"`
	QuantityProduced      pgtype.Numeric   `json:"quantity_produced"`
	ProductionDate        pgtype.Timestamp `json:"production_date"`
	OperatorShift         string           `json:"operator_shift"`
}

func (q *Queries) CreateProductionBatch(ctx context.Context, arg CreateProductionBatchParams) (ProductionBatch, error) {
	row := q.db.QueryRow(ctx, createProductionBatch,
		arg.BatchNumber,
		arg.ProductionOrderNumber,
		arg.ProductType,
		arg.QuantityProduced,
		arg.ProductionDate,
		arg.OperatorShift,
	)
	var i ProductionBatch
	err := row.Scan(
		&i.BatchNumber,
		&i.ProductionOrderNumber,
		&i.ProductType,
		&i.QuantityProduced,
		&i.ProductionDate,
		&i.OperatorShift,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchSlitCoilMapByBatchAndSlit = `-- name: GetBatchSlitCoilMapByBatchAndSlit :one
SELECT id, "batchNumber", "slitCoilId", "quantityConsumed", "createdAt"
FROM "BatchSlitCoilMap"
WHERE "batchNumber" = $1
  AND "slitCoilId" = $2
`

type GetBatchSlitCoilMapByBatchAndSlitParams struct {
	BatchNumber string `json:"batch_number"`
	SlitCoilID  string `json:"slit_coil_id"`
}

func (q *Queries) GetBatchSlitCoilMapByBatchAndSlit(ctx context.Context, arg GetBatchSlitCoilMapByBatchAndSlitParams) (BatchSlitCoilMap, error) {
	row := q.db.QueryRow(ctx, getBatchSlitCoilMapByBatchAndSlit, arg.BatchNumber, arg.SlitCoilID)
	var i BatchSlitCoilMap
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.SlitCoilId,
		&i.QuantityConsumed,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBatchNumberWithPrefix = `-- name: GetLatestBatchNumberWithPrefix :one
SELECT "batchNumber"
FROM "ProductionBatch"
WHERE "batchNumber" LIKE $1 || '%'
ORDER BY "batchNumber" DESC
LIMIT 1
`

func (q *Queries) GetLatestBatchNumberWithPrefix(ctx context.Context, prefix pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getLatestBatchNumberWithPrefix, prefix)
	var batchNumber string
	err := row.Scan(&batchNumber)
	return batchNumber, err
}

const getProductionBatchByNumber = `-- name: GetProductionBatchByNumber :one
SELECT "batchNumber", "productionOrderNumber", "productType", "quantityProduced", "productionDate", "operatorShift", "createdAt", "updatedAt"
FROM "ProductionBatch"
WHERE "batchNumber" = $1
`

func (q *Queries) GetProductionBatchByNumber(ctx context.Context, batchNumber string) (ProductionBatch, error) {
	row := q.db.QueryRow(ctx, getProductionBatchByNumber, batchNumber)
	var i ProductionBatch
	err := row.Scan(
		&i.BatchNumber,
		&i.ProductionOrderNumber,
		&i.ProductType,
		&i.QuantityProduced,
		&i.ProductionDate,
		&i.OperatorShift,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlitCoilProductionContext = `-- name: GetSlitCoilProductionContext :one
SELECT
    sr."slitCoilId",
    sr."slitCoilWeight",
    srr.id AS receipt_id,
    srr."inspectionResult"
FROM "SlittingRecord" sr
LEFT JOIN "SunrackReceipt" srr ON srr."slitCoilId" = sr."slitCoilId"
WHERE sr."slitCoilId" = $1
`

type GetSlitCoilProductionContextRow struct {
	SlitCoilId       string               `json:"slitCoilId"`
	SlitCoilWeight   pgtype.Numeric       `json:"slitCoilWeight"`
	ReceiptID        pgtype.Text          `json:"receipt_id"`
	InspectionResult NullInspectionResult `json:"inspectionResult"`
}

func (q *Queries) GetSlitCoilProductionContext(ctx context.Context, slitCoilID string) (GetSlitCoilProductionContextRow, error) {
	row := q.db.QueryRow(ctx, getSlitCoilProductionContext, slitCoilID)
	var i GetSlitCoilProductionContextRow
	err := row.Scan(
		&i.SlitCoilId,
		&i.SlitCoilWeight,
		&i.ReceiptID,
		&i.InspectionResult,
	)
	return i, err
}

const listBatchSlitCoilMapsForBatch = `-- name: ListBatchSlitCoilMapsForBatch :many
SELECT id, "batchNumber", "slitCoilId", "quantityConsumed", "createdAt"
FROM "BatchSlitCoilMap"
WHERE "batchNumber" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListBatchSlitCoilMapsForBatch(ctx context.Context, batchNumber string) ([]BatchSlitCoilMap, error) {
	rows, err := q.db.Query(ctx, listBatchSlitCoilMapsForBatch, batchNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchSlitCoilMap{}
	for rows.Next() {
		var i BatchSlitCoilMap
		if err := rows.Scan(
			&i.ID,
			&i.BatchNumber,
			&i.SlitCoilId,
			&i.QuantityConsumed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlitCoilProductionConsumptions = `-- name: ListSlitCoilProductionConsumptions :many
SELECT
    m.id,
    m."batchNumber",
    m."slitCoilId",
    m."quantityConsumed",
    m."createdAt",
    b."productType",
    b."quantityProduced",
    b."productionDate",
    b."productionOrderNumber"
FROM "BatchSlitCoilMap" m
INNER JOIN "ProductionBatch" b ON b."batchNumber" = m."batchNumber"
WHERE m."slitCoilId" = $1
ORDER BY m."createdAt" ASC
`

type ListSlitCoilProductionConsumptionsRow struct {
	ID                    string           `json:"id"`
	BatchNumber           string           `json:"batchNumber"`
	SlitCoilId            string           `json:"slitCoilId"`
	QuantityConsumed      pgtype.Numeric   `json:"quantityConsumed"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	ProductType           string           `json:"productType"`
	QuantityProduced      pgtype.Numeric   `json:"quantityProduced"`
	ProductionDate        pgtype.Timestamp `json:"productionDate"`
	ProductionOrderNumber string           `json:"productionOrderNumber"`
}

func (q *Queries) ListSlitCoilProductionConsumptions(ctx context.Context, slitCoilID string) ([]ListSlitCoilProductionConsumptionsRow, error) {
	rows, err := q.db.Query(ctx, listSlitCoilProductionConsumptions, slitCoilID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlitCoilProductionConsumptionsRow{}
	for rows.Next() {
		var i ListSlitCoilProductionConsumptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchNumber,
			&i.SlitCoilId,
			&i.QuantityConsumed,
			&i.CreatedAt,
			&i.ProductType,
			&i.QuantityProduced,
			&i.ProductionDate,
			&i.ProductionOrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productionBatchExists = `-- name: ProductionBatchExists :one
SELECT EXISTS(
    SELECT 1 FROM "ProductionBatch" WHERE "batchNumber" = $1
)::bool AS exists
`

func (q *Queries) ProductionBatchExists(ctx context.Context, batchNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, productionBatchExists, batchNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sumConsumedBySlitCoil = `-- name: SumConsumedBySlitCoil :one
SELECT COALESCE(SUM("quantityConsumed"), 0)::numeric AS total
FROM "BatchSlitCoilMap"
WHERE "slitCoilId" = $1
  AND (
    $2::text IS NULL
    OR $2::text = ''
    OR "batchNumber" != $2
  )
`

type SumConsumedBySlitCoilParams struct {
	SlitCoilID   string      `json:"slit_coil_id"`
	ExcludeBatch pgtype.Text `json:"exclude_batch"`
}

func (q *Queries) SumConsumedBySlitCoil(ctx context.Context, arg SumConsumedBySlitCoilParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumConsumedBySlitCoil, arg.SlitCoilID, arg.ExcludeBatch)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateProductionBatch = `-- name: UpdateProductionBatch :one
UPDATE "ProductionBatch"
SET
    "productionOrderNumber" = COALESCE($1, "productionOrderNumber"),
    "productType" = COALESCE($2, "productType"),
    "quantityProduced" = COALESCE($3, "quantityProduced"),
    "productionDate" = COALESCE($4, "productionDate"),
    "operatorShift" = COALESCE($5, "operatorShift"),
    "updatedAt" = NOW()
WHERE "batchNumber" = $6
RETURNING "batchNumber", "productionOrderNumber", "productType", "quantityProduced", "productionDate", "operatorShift", "createdAt", "updatedAt"
`

type UpdateProductionBatchParams struct {
	ProductionOrderNumber pgtype.Text      `json:"production_order_number"`
	ProductType           pgtype.Text      `json:"product_type"`
	QuantityProduced      pgtype.Numeric   `json:"quantity_produced"`
	ProductionDate        pgtype.Timestamp `json:"production_date"`
	OperatorShift         pgtype.Text      `json:"operator_shift"`
	BatchNumber           string           `json:"batch_number"`
}

func (q *Queries) UpdateProductionBatch(ctx context.Context, arg UpdateProductionBatchParams) (ProductionBatch, error) {
	row := q.db.QueryRow(ctx, updateProductionBatch,
		arg.ProductionOrderNumber,
		arg.ProductType,
		arg.QuantityProduced,
		arg.ProductionDate,
		arg.OperatorShift,
		arg.BatchNumber,
	)
	var i ProductionBatch
	err := row.Scan(
		&i.BatchNumber,
		&i.ProductionOrderNumber,
		&i.ProductType,
		&i.QuantityProduced,
		&i.ProductionDate,
		&i.OperatorShift,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
