// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBatchesWithNoQc = `-- name: CountBatchesWithNoQc :one
SELECT COUNT(*)::bigint AS count
FROM "ProductionBatch" pb
WHERE NOT EXISTS (
    SELECT 1 FROM "QCInspection" qi WHERE qi."batchNumber" = pb."batchNumber"
)
`

func (q *Queries) CountBatchesWithNoQc(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBatchesWithNoQc)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQcInspections = `-- name: CountQcInspections :one
SELECT COUNT(*)::bigint AS count FROM "QCInspection"
`

func (q *Queries) CountQcInspections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQcInspections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQcInspectionsByResult = `-- name: CountQcInspectionsByResult :one
SELECT COUNT(*)::bigint AS count
FROM "QCInspection"
WHERE "qcResult" = $1
`

func (q *Queries) CountQcInspectionsByResult(ctx context.Context, qcResult QcResult) (int64, error) {
	row := q.db.QueryRow(ctx, countQcInspectionsByResult, qcResult)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQcInspection = `-- name: CreateQcInspection :one
INSERT INTO "QCInspection" (
    id,
    "batchNumber",
    "qcResult",
    "inspectorName",
    "inspectionDate",
    "qcRemarks",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING id, "batchNumber", "qcResult", "inspectorName", "inspectionDate", "qcRemarks", "createdAt", "updatedAt"
`

type CreateQcInspectionParams struct {
	ID             string           `json:"id"`
	BatchNumber    string           `json:"batch_number"`
	QcResult       QcResult         `json:"qc_result"`
	InspectorName  string           `json:"inspector_name"`
	InspectionDate pgtype.Timestamp `json:"inspection_date"`
	QcRemarks      pgtype.Text      `json:"qc_remarks"`
}

func (q *Queries) CreateQcInspection(ctx context.Context, arg CreateQcInspectionParams) (QCInspection, error) {
	row := q.db.QueryRow(ctx, createQcInspection,
		arg.ID,
		arg.BatchNumber,
		arg.QcResult,
		arg.InspectorName,
		arg.InspectionDate,
		arg.QcRemarks,
	)
	var i QCInspection
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.QcResult,
		&i.InspectorName,
		&i.InspectionDate,
		&i.QcRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQcInspectionPhoto = `-- name: CreateQcInspectionPhoto :one
INSERT INTO "QCInspectionPhoto" (
    id,
    "inspectionId",
    filename,
    "originalName",
    mimetype,
    size,
    "storagePath",
    "uploadedById",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW()
)
RETURNING id, "inspectionId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
`

type CreateQcInspectionPhotoParams struct {
	ID           string      `json:"id"`
	InspectionID string      `json:"inspection_id"`
	Filename     string      `json:"filename"`
	OriginalName string      `json:"original_name"`
	Mimetype     string      `json:"mimetype"`
	Size         int32       `json:"size"`
	StoragePath  string      `json:"storage_path"`
	UploadedByID pgtype.Text `json:"uploaded_by_id"`
}

func (q *Queries) CreateQcInspectionPhoto(ctx context.Context, arg CreateQcInspectionPhotoParams) (QCInspectionPhoto, error) {
	row := q.db.QueryRow(ctx, createQcInspectionPhoto,
		arg.ID,
		arg.InspectionID,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
		arg.StoragePath,
		arg.UploadedByID,
	)
	var i QCInspectionPhoto
	err := row.Scan(
		&i.ID,
		&i.InspectionId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestQcInspectionByBatch = `-- name: GetLatestQcInspectionByBatch :one
SELECT id, "batchNumber", "qcResult", "inspectorName", "inspectionDate", "qcRemarks", "createdAt", "updatedAt"
FROM "QCInspection"
WHERE "batchNumber" = $1
ORDER BY "inspectionDate" DESC
LIMIT 1
`

func (q *Queries) GetLatestQcInspectionByBatch(ctx context.Context, batchNumber string) (QCInspection, error) {
	row := q.db.QueryRow(ctx, getLatestQcInspectionByBatch, batchNumber)
	var i QCInspection
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.QcResult,
		&i.InspectorName,
		&i.InspectionDate,
		&i.QcRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQcInspectionByID = `-- name: GetQcInspectionByID :one
SELECT id, "batchNumber", "qcResult", "inspectorName", "inspectionDate", "qcRemarks", "createdAt", "updatedAt"
FROM "QCInspection"
WHERE id = $1
`

func (q *Queries) GetQcInspectionByID(ctx context.Context, id string) (QCInspection, error) {
	row := q.db.QueryRow(ctx, getQcInspectionByID, id)
	var i QCInspection
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.QcResult,
		&i.InspectorName,
		&i.InspectionDate,
		&i.QcRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQcInspectionPhotoByID = `-- name: GetQcInspectionPhotoByID :one
SELECT id, "inspectionId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "QCInspectionPhoto"
WHERE id = $1
`

func (q *Queries) GetQcInspectionPhotoByID(ctx context.Context, id string) (QCInspectionPhoto, error) {
	row := q.db.QueryRow(ctx, getQcInspectionPhotoByID, id)
	var i QCInspectionPhoto
	err := row.Scan(
		&i.ID,
		&i.InspectionId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const listQcInspectionPhotosByInspectionID = `-- name: ListQcInspectionPhotosByInspectionID :many
SELECT id, "inspectionId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "QCInspectionPhoto"
WHERE "inspectionId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListQcInspectionPhotosByInspectionID(ctx context.Context, inspectionID string) ([]QCInspectionPhoto, error) {
	rows, err := q.db.Query(ctx, listQcInspectionPhotosByInspectionID, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QCInspectionPhoto{}
	for rows.Next() {
		var i QCInspectionPhoto
		if err := rows.Scan(
			&i.ID,
			&i.InspectionId,
			&i.Filename,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.StoragePath,
			&i.UploadedById,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQcInspectionsByBatch = `-- name: ListQcInspectionsByBatch :many
SELECT id, "batchNumber", "qcResult", "inspectorName", "inspectionDate", "qcRemarks", "createdAt", "updatedAt"
FROM "QCInspection"
WHERE "batchNumber" = $1
ORDER BY "inspectionDate" DESC
`

func (q *Queries) ListQcInspectionsByBatch(ctx context.Context, batchNumber string) ([]QCInspection, error) {
	rows, err := q.db.Query(ctx, listQcInspectionsByBatch, batchNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QCInspection{}
	for rows.Next() {
		var i QCInspection
		if err := rows.Scan(
			&i.ID,
			&i.BatchNumber,
			&i.QcResult,
			&i.InspectorName,
			&i.InspectionDate,
			&i.QcRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQcInspection = `-- name: UpdateQcInspection :one
UPDATE "QCInspection"
SET
    "qcResult" = COALESCE($1, "qcResult"),
    "inspectorName" = COALESCE($2, "inspectorName"),
    "inspectionDate" = COALESCE($3, "inspectionDate"),
    "qcRemarks" = COALESCE($4, "qcRemarks"),
    "updatedAt" = NOW()
WHERE id = $5
RETURNING id, "batchNumber", "qcResult", "inspectorName", "inspectionDate", "qcRemarks", "createdAt", "updatedAt"
`

type UpdateQcInspectionParams struct {
	QcResult       NullQcResult     `json:"qc_result"`
	InspectorName  pgtype.Text      `json:"inspector_name"`
	InspectionDate pgtype.Timestamp `json:"inspection_date"`
	QcRemarks      pgtype.Text      `json:"qc_remarks"`
	ID             string           `json:"id"`
}

func (q *Queries) UpdateQcInspection(ctx context.Context, arg UpdateQcInspectionParams) (QCInspection, error) {
	row := q.db.QueryRow(ctx, updateQcInspection,
		arg.QcResult,
		arg.InspectorName,
		arg.InspectionDate,
		arg.QcRemarks,
		arg.ID,
	)
	var i QCInspection
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.QcResult,
		&i.InspectorName,
		&i.InspectionDate,
		&i.QcRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
