// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description
FROM "Role"
WHERE code = $1
`

type GetRoleByCodeRow struct {
	ID          string      `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i GetRoleByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listAllRolePermissions = `-- name: ListAllRolePermissions :many
SELECT "roleId", module, access
FROM "RoleModulePermission"
ORDER BY "roleId", module
`

type ListAllRolePermissionsRow struct {
	RoleId string       `json:"roleId"`
	Module string       `json:"module"`
	Access ModuleAccess `json:"access"`
}

func (q *Queries) ListAllRolePermissions(ctx context.Context) ([]ListAllRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRolePermissionsRow{}
	for rows.Next() {
		var i ListAllRolePermissionsRow
		if err := rows.Scan(&i.RoleId, &i.Module, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRoleCode = `-- name: ListPermissionsByRoleCode :many
SELECT p.module, p.access
FROM "RoleModulePermission" p
INNER JOIN "Role" r ON r.id = p."roleId"
WHERE r.code = $1
ORDER BY p.module
`

type ListPermissionsByRoleCodeRow struct {
	Module string       `json:"module"`
	Access ModuleAccess `json:"access"`
}

func (q *Queries) ListPermissionsByRoleCode(ctx context.Context, code string) ([]ListPermissionsByRoleCodeRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleCode, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsByRoleCodeRow{}
	for rows.Next() {
		var i ListPermissionsByRoleCodeRow
		if err := rows.Scan(&i.Module, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT
    r.id,
    r.code,
    r.name,
    r.description,
    COUNT(u.id)::bigint AS user_count
FROM "Role" r
LEFT JOIN "User" u ON u."roleId" = r.id
GROUP BY r.id, r.code, r.name, r.description
ORDER BY r.name ASC
`

type ListRolesRow struct {
	ID          string      `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	UserCount   int64       `json:"user_count"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoleModulePermission = `-- name: UpsertRoleModulePermission :exec
INSERT INTO "RoleModulePermission" (id, "roleId", module, access)
VALUES ($1, $2, $3, $4)
ON CONFLICT ("roleId", module)
DO UPDATE SET access = EXCLUDED.access
`

type UpsertRoleModulePermissionParams struct {
	ID     string       `json:"id"`
	RoleID string       `json:"role_id"`
	Module string       `json:"module"`
	Access ModuleAccess `json:"access"`
}

func (q *Queries) UpsertRoleModulePermission(ctx context.Context, arg UpsertRoleModulePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertRoleModulePermission,
		arg.ID,
		arg.RoleID,
		arg.Module,
		arg.Access,
	)
	return err
}
