// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_installation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingDispatches = `-- name: CountPendingDispatches :one
SELECT COUNT(*)::bigint AS count
FROM "SiteDispatch" sd
WHERE NOT EXISTS (
    SELECT 1 FROM "SiteInstallation" si WHERE si."dispatchNoteNumber" = sd."dispatchNoteNumber"
)
`

func (q *Queries) CountPendingDispatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingDispatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteInstallationPhotos = `-- name: CountSiteInstallationPhotos :one
SELECT COUNT(*)::bigint AS count FROM "SiteInstallationPhoto"
`

func (q *Queries) CountSiteInstallationPhotos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSiteInstallationPhotos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteInstallationPhotosByInstallationID = `-- name: CountSiteInstallationPhotosByInstallationID :one
SELECT COUNT(*)::bigint AS count
FROM "SiteInstallationPhoto"
WHERE "installationId" = $1
`

func (q *Queries) CountSiteInstallationPhotosByInstallationID(ctx context.Context, installationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSiteInstallationPhotosByInstallationID, installationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSiteInstallations = `-- name: CountSiteInstallations :one
SELECT COUNT(*)::bigint AS count FROM "SiteInstallation"
`

func (q *Queries) CountSiteInstallations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSiteInstallations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSiteInstallation = `-- name: CreateSiteInstallation :one
INSERT INTO "SiteInstallation" (
    id,
    "dispatchNoteNumber",
    "siteReceiptDate",
    "installationDate",
    "installerEpcPartner",
    "quantityInstalled",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING id, "dispatchNoteNumber", "siteReceiptDate", "installationDate", "installerEpcPartner", "quantityInstalled", "createdAt", "updatedAt"
`

type CreateSiteInstallationParams struct {
	ID                  string           `json:"id"`
	DispatchNoteNumber  string           `json:"dispatch_note_number"`
	SiteReceiptDate     pgtype.Timestamp `json:"site_receipt_date"`
	InstallationDate    pgtype.Timestamp `json:"installation_date"`
	InstallerEpcPartner string           `json:"installer_epc_partner"`
	QuantityInstalled   pgtype.Numeric   `json:"quantity_installed"`
}

func (q *Queries) CreateSiteInstallation(ctx context.Context, arg CreateSiteInstallationParams) (SiteInstallation, error) {
	row := q.db.QueryRow(ctx, createSiteInstallation,
		arg.ID,
		arg.DispatchNoteNumber,
		arg.SiteReceiptDate,
		arg.InstallationDate,
		arg.InstallerEpcPartner,
		arg.QuantityInstalled,
	)
	var i SiteInstallation
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.SiteReceiptDate,
		&i.InstallationDate,
		&i.InstallerEpcPartner,
		&i.QuantityInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSiteInstallationPhoto = `-- name: CreateSiteInstallationPhoto :one
INSERT INTO "SiteInstallationPhoto" (
    id,
    "installationId",
    filename,
    "originalName",
    mimetype,
    size,
    "storagePath",
    "uploadedById",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW()
)
RETURNING id, "installationId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
`

type CreateSiteInstallationPhotoParams struct {
	ID             string      `json:"id"`
	InstallationID string      `json:"installation_id"`
	Filename       string      `json:"filename"`
	OriginalName   string      `json:"original_name"`
	Mimetype       string      `json:"mimetype"`
	Size           int32       `json:"size"`
	StoragePath    string      `json:"storage_path"`
	UploadedByID   pgtype.Text `json:"uploaded_by_id"`
}

func (q *Queries) CreateSiteInstallationPhoto(ctx context.Context, arg CreateSiteInstallationPhotoParams) (SiteInstallationPhoto, error) {
	row := q.db.QueryRow(ctx, createSiteInstallationPhoto,
		arg.ID,
		arg.InstallationID,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
		arg.StoragePath,
		arg.UploadedByID,
	)
	var i SiteInstallationPhoto
	err := row.Scan(
		&i.ID,
		&i.InstallationId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteInstallationByDispatchNote = `-- name: GetSiteInstallationByDispatchNote :one
SELECT id, "dispatchNoteNumber", "siteReceiptDate", "installationDate", "installerEpcPartner", "quantityInstalled", "createdAt", "updatedAt"
FROM "SiteInstallation"
WHERE "dispatchNoteNumber" = $1
`

func (q *Queries) GetSiteInstallationByDispatchNote(ctx context.Context, dispatchNoteNumber string) (SiteInstallation, error) {
	row := q.db.QueryRow(ctx, getSiteInstallationByDispatchNote, dispatchNoteNumber)
	var i SiteInstallation
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.SiteReceiptDate,
		&i.InstallationDate,
		&i.InstallerEpcPartner,
		&i.QuantityInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteInstallationByID = `-- name: GetSiteInstallationByID :one
SELECT id, "dispatchNoteNumber", "siteReceiptDate", "installationDate", "installerEpcPartner", "quantityInstalled", "createdAt", "updatedAt"
FROM "SiteInstallation"
WHERE id = $1
`

func (q *Queries) GetSiteInstallationByID(ctx context.Context, id string) (SiteInstallation, error) {
	row := q.db.QueryRow(ctx, getSiteInstallationByID, id)
	var i SiteInstallation
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.SiteReceiptDate,
		&i.InstallationDate,
		&i.InstallerEpcPartner,
		&i.QuantityInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteInstallationPhotoByID = `-- name: GetSiteInstallationPhotoByID :one
SELECT id, "installationId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "SiteInstallationPhoto"
WHERE id = $1
`

func (q *Queries) GetSiteInstallationPhotoByID(ctx context.Context, id string) (SiteInstallationPhoto, error) {
	row := q.db.QueryRow(ctx, getSiteInstallationPhotoByID, id)
	var i SiteInstallationPhoto
	err := row.Scan(
		&i.ID,
		&i.InstallationId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const listSiteInstallationPhotosByInstallationID = `-- name: ListSiteInstallationPhotosByInstallationID :many
SELECT id, "installationId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "SiteInstallationPhoto"
WHERE "installationId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListSiteInstallationPhotosByInstallationID(ctx context.Context, installationID string) ([]SiteInstallationPhoto, error) {
	rows, err := q.db.Query(ctx, listSiteInstallationPhotosByInstallationID, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteInstallationPhoto{}
	for rows.Next() {
		var i SiteInstallationPhoto
		if err := rows.Scan(
			&i.ID,
			&i.InstallationId,
			&i.Filename,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.StoragePath,
			&i.UploadedById,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumQuantityInstalled = `-- name: SumQuantityInstalled :one
SELECT COALESCE(SUM("quantityInstalled"), 0)::numeric AS total
FROM "SiteInstallation"
`

func (q *Queries) SumQuantityInstalled(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumQuantityInstalled)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateSiteInstallation = `-- name: UpdateSiteInstallation :one
UPDATE "SiteInstallation"
SET
    "siteReceiptDate" = COALESCE($1, "siteReceiptDate"),
    "installationDate" = COALESCE($2, "installationDate"),
    "installerEpcPartner" = COALESCE($3, "installerEpcPartner"),
    "quantityInstalled" = COALESCE($4, "quantityInstalled"),
    "updatedAt" = NOW()
WHERE id = $5
RETURNING id, "dispatchNoteNumber", "siteReceiptDate", "installationDate", "installerEpcPartner", "quantityInstalled", "createdAt", "updatedAt"
`

type UpdateSiteInstallationParams struct {
	SiteReceiptDate     pgtype.Timestamp `json:"site_receipt_date"`
	InstallationDate    pgtype.Timestamp `json:"installation_date"`
	InstallerEpcPartner pgtype.Text      `json:"installer_epc_partner"`
	QuantityInstalled   pgtype.Numeric   `json:"quantity_installed"`
	ID                  string           `json:"id"`
}

func (q *Queries) UpdateSiteInstallation(ctx context.Context, arg UpdateSiteInstallationParams) (SiteInstallation, error) {
	row := q.db.QueryRow(ctx, updateSiteInstallation,
		arg.SiteReceiptDate,
		arg.InstallationDate,
		arg.InstallerEpcPartner,
		arg.QuantityInstalled,
		arg.ID,
	)
	var i SiteInstallation
	err := row.Scan(
		&i.ID,
		&i.DispatchNoteNumber,
		&i.SiteReceiptDate,
		&i.InstallationDate,
		&i.InstallerEpcPartner,
		&i.QuantityInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
