// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slitting.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSlittingRecord = `-- name: CreateSlittingRecord :one
INSERT INTO "SlittingRecord" (
    "slitCoilId",
    "parentCoilNumber",
    "slitWidthSize",
    "slittingDate",
    "slitCoilWeight",
    "slitterLocation",
    "dispatchNote",
    "vehicleNumber",
    "transporterName",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, 'Shiv Sagar Slitter'),
    $7,
    $8,
    $9,
    NOW(),
    NOW()
)
RETURNING "slitCoilId", "parentCoilNumber", "slitWidthSize", "slittingDate", "slitCoilWeight", "slitterLocation", "dispatchNote", "vehicleNumber", "transporterName", "createdAt", "updatedAt"
`

type CreateSlittingRecordParams struct {
	SlitCoilID       string           `json:"slit_coil_id"`
	ParentCoilNumber string           `json:"parent_coil_number"`
	SlitWidthSize    string           `json:"slit_width_size"`
	SlittingDate     pgtype.Timestamp `json:"slitting_date"`
	SlitCoilWeight   pgtype.Numeric   `json:"slit_coil_weight"`
	SlitterLocation  interface{}      `json:"slitter_location"`
	DispatchNote     pgtype.Text      `json:"dispatch_note"`
	VehicleNumber    pgtype.Text      `json:"vehicle_number"`
	TransporterName  pgtype.Text      `json:"transporter_name"`
}

func (q *Queries) CreateSlittingRecord(ctx context.Context, arg CreateSlittingRecordParams) (SlittingRecord, error) {
	row := q.db.QueryRow(ctx, createSlittingRecord,
		arg.SlitCoilID,
		arg.ParentCoilNumber,
		arg.SlitWidthSize,
		arg.SlittingDate,
		arg.SlitCoilWeight,
		arg.SlitterLocation,
		arg.DispatchNote,
		arg.VehicleNumber,
		arg.TransporterName,
	)
	var i SlittingRecord
	err := row.Scan(
		&i.SlitCoilId,
		&i.ParentCoilNumber,
		&i.SlitWidthSize,
		&i.SlittingDate,
		&i.SlitCoilWeight,
		&i.SlitterLocation,
		&i.DispatchNote,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentCoilStatus = `-- name: GetParentCoilStatus :one
SELECT status
FROM "Coil"
WHERE "coilNumber" = $1
`

func (q *Queries) GetParentCoilStatus(ctx context.Context, coilNumber string) (CoilStatus, error) {
	row := q.db.QueryRow(ctx, getParentCoilStatus, coilNumber)
	var status CoilStatus
	err := row.Scan(&status)
	return status, err
}

const getSlittingBySlitCoilId = `-- name: GetSlittingBySlitCoilId :one
SELECT "slitCoilId", "parentCoilNumber", "slitWidthSize", "slittingDate", "slitCoilWeight", "slitterLocation", "dispatchNote", "vehicleNumber", "transporterName", "createdAt", "updatedAt"
FROM "SlittingRecord"
WHERE "slitCoilId" = $1
`

func (q *Queries) GetSlittingBySlitCoilId(ctx context.Context, slitCoilID string) (SlittingRecord, error) {
	row := q.db.QueryRow(ctx, getSlittingBySlitCoilId, slitCoilID)
	var i SlittingRecord
	err := row.Scan(
		&i.SlitCoilId,
		&i.ParentCoilNumber,
		&i.SlitWidthSize,
		&i.SlittingDate,
		&i.SlitCoilWeight,
		&i.SlitterLocation,
		&i.DispatchNote,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSlitCoilIdsForParent = `-- name: ListSlitCoilIdsForParent :many
SELECT "slitCoilId"
FROM "SlittingRecord"
WHERE "parentCoilNumber" = $1
ORDER BY "slitCoilId" DESC
`

func (q *Queries) ListSlitCoilIdsForParent(ctx context.Context, parentCoilNumber string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSlitCoilIdsForParent, parentCoilNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slitCoilId string
		if err := rows.Scan(&slitCoilId); err != nil {
			return nil, err
		}
		items = append(items, slitCoilId)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slittingExists = `-- name: SlittingExists :one
SELECT EXISTS(
    SELECT 1 FROM "SlittingRecord" WHERE "slitCoilId" = $1
)::bool AS exists
`

func (q *Queries) SlittingExists(ctx context.Context, slitCoilID string) (bool, error) {
	row := q.db.QueryRow(ctx, slittingExists, slitCoilID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSlittingRecord = `-- name: UpdateSlittingRecord :one
UPDATE "SlittingRecord"
SET
    "slitWidthSize" = COALESCE($1, "slitWidthSize"),
    "slittingDate" = COALESCE($2, "slittingDate"),
    "slitCoilWeight" = COALESCE($3, "slitCoilWeight"),
    "slitterLocation" = COALESCE($4, "slitterLocation"),
    "dispatchNote" = COALESCE($5, "dispatchNote"),
    "vehicleNumber" = COALESCE($6, "vehicleNumber"),
    "transporterName" = COALESCE($7, "transporterName"),
    "updatedAt" = NOW()
WHERE "slitCoilId" = $8
RETURNING "slitCoilId", "parentCoilNumber", "slitWidthSize", "slittingDate", "slitCoilWeight", "slitterLocation", "dispatchNote", "vehicleNumber", "transporterName", "createdAt", "updatedAt"
`

type UpdateSlittingRecordParams struct {
	SlitWidthSize   pgtype.Text      `json:"slit_width_size"`
	SlittingDate    pgtype.Timestamp `json:"slitting_date"`
	SlitCoilWeight  pgtype.Numeric   `json:"slit_coil_weight"`
	SlitterLocation pgtype.Text      `json:"slitter_location"`
	DispatchNote    pgtype.Text      `json:"dispatch_note"`
	VehicleNumber   pgtype.Text      `json:"vehicle_number"`
	TransporterName pgtype.Text      `json:"transporter_name"`
	SlitCoilID      string           `json:"slit_coil_id"`
}

func (q *Queries) UpdateSlittingRecord(ctx context.Context, arg UpdateSlittingRecordParams) (SlittingRecord, error) {
	row := q.db.QueryRow(ctx, updateSlittingRecord,
		arg.SlitWidthSize,
		arg.SlittingDate,
		arg.SlitCoilWeight,
		arg.SlitterLocation,
		arg.DispatchNote,
		arg.VehicleNumber,
		arg.TransporterName,
		arg.SlitCoilID,
	)
	var i SlittingRecord
	err := row.Scan(
		&i.SlitCoilId,
		&i.ParentCoilNumber,
		&i.SlitWidthSize,
		&i.SlittingDate,
		&i.SlitCoilWeight,
		&i.SlitterLocation,
		&i.DispatchNote,
		&i.VehicleNumber,
		&i.TransporterName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
