// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sunrack_receipt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingSlitCoils = `-- name: CountPendingSlitCoils :one
SELECT COUNT(*)::bigint AS count
FROM "SlittingRecord" sr
LEFT JOIN "SunrackReceipt" srr ON srr."slitCoilId" = sr."slitCoilId"
WHERE srr.id IS NULL
`

func (q *Queries) CountPendingSlitCoils(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSlitCoils)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSunrackReceiptsByInspection = `-- name: CountSunrackReceiptsByInspection :one
SELECT COUNT(*)::bigint AS count
FROM "SunrackReceipt"
WHERE "inspectionResult" = $1
`

func (q *Queries) CountSunrackReceiptsByInspection(ctx context.Context, inspectionResult InspectionResult) (int64, error) {
	row := q.db.QueryRow(ctx, countSunrackReceiptsByInspection, inspectionResult)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSunrackReceiptsTotal = `-- name: CountSunrackReceiptsTotal :one
SELECT COUNT(*)::bigint AS count FROM "SunrackReceipt"
`

func (q *Queries) CountSunrackReceiptsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSunrackReceiptsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSunrackReceipt = `-- name: CreateSunrackReceipt :one
INSERT INTO "SunrackReceipt" (
    id,
    "slitCoilId",
    "receiptDateSunrack",
    "storageLocationBin",
    "inspectionResult",
    "inspectionRemarks",
    "confirmedDispatchNote",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW(),
    NOW()
)
RETURNING id, "slitCoilId", "receiptDateSunrack", "storageLocationBin", "inspectionResult", "inspectionRemarks", "confirmedDispatchNote", "createdAt", "updatedAt"
`

type CreateSunrackReceiptParams struct {
	ID                    string           `json:"id"`
	SlitCoilID            string           `json:"slit_coil_id"`
	ReceiptDateSunrack    pgtype.Timestamp `json:"receipt_date_sunrack"`
	StorageLocationBin    string           `json:"storage_location_bin"`
	InspectionResult      InspectionResult `json:"inspection_result"`
	InspectionRemarks     pgtype.Text      `json:"inspection_remarks"`
	ConfirmedDispatchNote pgtype.Text      `json:"confirmed_dispatch_note"`
}

func (q *Queries) CreateSunrackReceipt(ctx context.Context, arg CreateSunrackReceiptParams) (SunrackReceipt, error) {
	row := q.db.QueryRow(ctx, createSunrackReceipt,
		arg.ID,
		arg.SlitCoilID,
		arg.ReceiptDateSunrack,
		arg.StorageLocationBin,
		arg.InspectionResult,
		arg.InspectionRemarks,
		arg.ConfirmedDispatchNote,
	)
	var i SunrackReceipt
	err := row.Scan(
		&i.ID,
		&i.SlitCoilId,
		&i.ReceiptDateSunrack,
		&i.StorageLocationBin,
		&i.InspectionResult,
		&i.InspectionRemarks,
		&i.ConfirmedDispatchNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSunrackReceiptPhoto = `-- name: CreateSunrackReceiptPhoto :one
INSERT INTO "SunrackReceiptPhoto" (
    id,
    "receiptId",
    filename,
    "originalName",
    mimetype,
    size,
    "storagePath",
    "uploadedById",
    "createdAt"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW()
)
RETURNING id, "receiptId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
`

type CreateSunrackReceiptPhotoParams struct {
	ID           string      `json:"id"`
	ReceiptID    string      `json:"receipt_id"`
	Filename     string      `json:"filename"`
	OriginalName string      `json:"original_name"`
	Mimetype     string      `json:"mimetype"`
	Size         int32       `json:"size"`
	StoragePath  string      `json:"storage_path"`
	UploadedByID pgtype.Text `json:"uploaded_by_id"`
}

func (q *Queries) CreateSunrackReceiptPhoto(ctx context.Context, arg CreateSunrackReceiptPhotoParams) (SunrackReceiptPhoto, error) {
	row := q.db.QueryRow(ctx, createSunrackReceiptPhoto,
		arg.ID,
		arg.ReceiptID,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
		arg.StoragePath,
		arg.UploadedByID,
	)
	var i SunrackReceiptPhoto
	err := row.Scan(
		&i.ID,
		&i.ReceiptId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const getSlittingDispatchNote = `-- name: GetSlittingDispatchNote :one
SELECT "dispatchNote"
FROM "SlittingRecord"
WHERE "slitCoilId" = $1
`

func (q *Queries) GetSlittingDispatchNote(ctx context.Context, slitCoilID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSlittingDispatchNote, slitCoilID)
	var dispatchNote pgtype.Text
	err := row.Scan(&dispatchNote)
	return dispatchNote, err
}

const getSunrackReceiptByID = `-- name: GetSunrackReceiptByID :one
SELECT id, "slitCoilId", "receiptDateSunrack", "storageLocationBin", "inspectionResult", "inspectionRemarks", "confirmedDispatchNote", "createdAt", "updatedAt"
FROM "SunrackReceipt"
WHERE id = $1
`

func (q *Queries) GetSunrackReceiptByID(ctx context.Context, id string) (SunrackReceipt, error) {
	row := q.db.QueryRow(ctx, getSunrackReceiptByID, id)
	var i SunrackReceipt
	err := row.Scan(
		&i.ID,
		&i.SlitCoilId,
		&i.ReceiptDateSunrack,
		&i.StorageLocationBin,
		&i.InspectionResult,
		&i.InspectionRemarks,
		&i.ConfirmedDispatchNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSunrackReceiptBySlitCoilId = `-- name: GetSunrackReceiptBySlitCoilId :one
SELECT id, "slitCoilId", "receiptDateSunrack", "storageLocationBin", "inspectionResult", "inspectionRemarks", "confirmedDispatchNote", "createdAt", "updatedAt"
FROM "SunrackReceipt"
WHERE "slitCoilId" = $1
`

func (q *Queries) GetSunrackReceiptBySlitCoilId(ctx context.Context, slitCoilID string) (SunrackReceipt, error) {
	row := q.db.QueryRow(ctx, getSunrackReceiptBySlitCoilId, slitCoilID)
	var i SunrackReceipt
	err := row.Scan(
		&i.ID,
		&i.SlitCoilId,
		&i.ReceiptDateSunrack,
		&i.StorageLocationBin,
		&i.InspectionResult,
		&i.InspectionRemarks,
		&i.ConfirmedDispatchNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSunrackReceiptPhotoByID = `-- name: GetSunrackReceiptPhotoByID :one
SELECT id, "receiptId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "SunrackReceiptPhoto"
WHERE id = $1
`

func (q *Queries) GetSunrackReceiptPhotoByID(ctx context.Context, id string) (SunrackReceiptPhoto, error) {
	row := q.db.QueryRow(ctx, getSunrackReceiptPhotoByID, id)
	var i SunrackReceiptPhoto
	err := row.Scan(
		&i.ID,
		&i.ReceiptId,
		&i.Filename,
		&i.OriginalName,
		&i.Mimetype,
		&i.Size,
		&i.StoragePath,
		&i.UploadedById,
		&i.CreatedAt,
	)
	return i, err
}

const listSunrackReceiptPhotosByReceiptID = `-- name: ListSunrackReceiptPhotosByReceiptID :many
SELECT id, "receiptId", filename, "originalName", mimetype, size, "storagePath", "uploadedById", "createdAt"
FROM "SunrackReceiptPhoto"
WHERE "receiptId" = $1
ORDER BY "createdAt" ASC
`

func (q *Queries) ListSunrackReceiptPhotosByReceiptID(ctx context.Context, receiptID string) ([]SunrackReceiptPhoto, error) {
	rows, err := q.db.Query(ctx, listSunrackReceiptPhotosByReceiptID, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SunrackReceiptPhoto{}
	for rows.Next() {
		var i SunrackReceiptPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptId,
			&i.Filename,
			&i.OriginalName,
			&i.Mimetype,
			&i.Size,
			&i.StoragePath,
			&i.UploadedById,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sunrackReceiptExistsForSlitCoil = `-- name: SunrackReceiptExistsForSlitCoil :one
SELECT EXISTS(
    SELECT 1 FROM "SunrackReceipt" WHERE "slitCoilId" = $1
)::bool AS exists
`

func (q *Queries) SunrackReceiptExistsForSlitCoil(ctx context.Context, slitCoilID string) (bool, error) {
	row := q.db.QueryRow(ctx, sunrackReceiptExistsForSlitCoil, slitCoilID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSunrackReceipt = `-- name: UpdateSunrackReceipt :one
UPDATE "SunrackReceipt"
SET
    "receiptDateSunrack" = COALESCE($1, "receiptDateSunrack"),
    "storageLocationBin" = COALESCE($2, "storageLocationBin"),
    "inspectionResult" = COALESCE($3, "inspectionResult"),
    "inspectionRemarks" = COALESCE($4, "inspectionRemarks"),
    "confirmedDispatchNote" = COALESCE($5, "confirmedDispatchNote"),
    "updatedAt" = NOW()
WHERE id = $6
RETURNING id, "slitCoilId", "receiptDateSunrack", "storageLocationBin", "inspectionResult", "inspectionRemarks", "confirmedDispatchNote", "createdAt", "updatedAt"
`

type UpdateSunrackReceiptParams struct {
	ReceiptDateSunrack    pgtype.Timestamp     `json:"receipt_date_sunrack"`
	StorageLocationBin    pgtype.Text          `json:"storage_location_bin"`
	InspectionResult      NullInspectionResult `json:"inspection_result"`
	InspectionRemarks     pgtype.Text          `json:"inspection_remarks"`
	ConfirmedDispatchNote pgtype.Text          `json:"confirmed_dispatch_note"`
	ID                    string               `json:"id"`
}

func (q *Queries) UpdateSunrackReceipt(ctx context.Context, arg UpdateSunrackReceiptParams) (SunrackReceipt, error) {
	row := q.db.QueryRow(ctx, updateSunrackReceipt,
		arg.ReceiptDateSunrack,
		arg.StorageLocationBin,
		arg.InspectionResult,
		arg.InspectionRemarks,
		arg.ConfirmedDispatchNote,
		arg.ID,
	)
	var i SunrackReceipt
	err := row.Scan(
		&i.ID,
		&i.SlitCoilId,
		&i.ReceiptDateSunrack,
		&i.StorageLocationBin,
		&i.InspectionResult,
		&i.InspectionRemarks,
		&i.ConfirmedDispatchNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
