// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traceability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listComplaintsForBatchTraceability = `-- name: ListComplaintsForBatchTraceability :many
SELECT
    c."complaintId",
    c."complaintDate",
    c."projectName",
    c."clientName",
    c."siteLocation",
    c."complaintDescription",
    c."rootCauseRemarks",
    c."resolutionStatus"::text AS resolution_status,
    c."resolutionDate",
    c."responsibleStage"::text AS responsible_stage
FROM "ComplaintBatchLine" cbl
INNER JOIN "Complaint" c ON c."complaintId" = cbl."complaintId"
WHERE cbl."batchNumber" = $1
`

type ListComplaintsForBatchTraceabilityRow struct {
	ComplaintId          string           `json:"complaintId"`
	ComplaintDate        pgtype.Timestamp `json:"complaintDate"`
	ProjectName          string           `json:"projectName"`
	ClientName           string           `json:"clientName"`
	SiteLocation         string           `json:"siteLocation"`
	ComplaintDescription string           `json:"complaintDescription"`
	RootCauseRemarks     pgtype.Text      `json:"rootCauseRemarks"`
	ResolutionStatus     string           `json:"resolution_status"`
	ResolutionDate       pgtype.Timestamp `json:"resolutionDate"`
	ResponsibleStage     string           `json:"responsible_stage"`
}

func (q *Queries) ListComplaintsForBatchTraceability(ctx context.Context, batchNumber string) ([]ListComplaintsForBatchTraceabilityRow, error) {
	rows, err := q.db.Query(ctx, listComplaintsForBatchTraceability, batchNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComplaintsForBatchTraceabilityRow{}
	for rows.Next() {
		var i ListComplaintsForBatchTraceabilityRow
		if err := rows.Scan(
			&i.ComplaintId,
			&i.ComplaintDate,
			&i.ProjectName,
			&i.ClientName,
			&i.SiteLocation,
			&i.ComplaintDescription,
			&i.RootCauseRemarks,
			&i.ResolutionStatus,
			&i.ResolutionDate,
			&i.ResponsibleStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchBatchLinesByBatchForTraceability = `-- name: ListDispatchBatchLinesByBatchForTraceability :many
SELECT
    dbl."dispatchNoteNumber",
    dbl."quantityDispatched",
    sd."dispatchDate",
    sd."projectName",
    sd."clientName",
    sd."siteLocation",
    sd."vehicleNumber",
    sd."transporterName"
FROM "DispatchBatchLine" dbl
INNER JOIN "SiteDispatch" sd ON sd."dispatchNoteNumber" = dbl."dispatchNoteNumber"
WHERE dbl."batchNumber" = $1
ORDER BY dbl."createdAt" ASC
`

type ListDispatchBatchLinesByBatchForTraceabilityRow struct {
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	QuantityDispatched pgtype.Numeric   `json:"quantityDispatched"`
	DispatchDate       pgtype.Timestamp `json:"dispatchDate"`
	ProjectName        string           `json:"projectName"`
	ClientName         string           `json:"clientName"`
	SiteLocation       string           `json:"siteLocation"`
	VehicleNumber      pgtype.Text      `json:"vehicleNumber"`
	TransporterName    pgtype.Text      `json:"transporterName"`
}

func (q *Queries) ListDispatchBatchLinesByBatchForTraceability(ctx context.Context, batchNumber string) ([]ListDispatchBatchLinesByBatchForTraceabilityRow, error) {
	rows, err := q.db.Query(ctx, listDispatchBatchLinesByBatchForTraceability, batchNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDispatchBatchLinesByBatchForTraceabilityRow{}
	for rows.Next() {
		var i ListDispatchBatchLinesByBatchForTraceabilityRow
		if err := rows.Scan(
			&i.DispatchNoteNumber,
			&i.QuantityDispatched,
			&i.DispatchDate,
			&i.ProjectName,
			&i.ClientName,
			&i.SiteLocation,
			&i.VehicleNumber,
			&i.TransporterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCoilsForBatch = `-- name: ListParentCoilsForBatch :many
SELECT DISTINCT sr."parentCoilNumber"
FROM "BatchSlitCoilMap" bcm
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = bcm."slitCoilId"
WHERE bcm."batchNumber" = $1
`

func (q *Queries) ListParentCoilsForBatch(ctx context.Context, batchNumber string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParentCoilsForBatch, batchNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parentCoilNumber string
		if err := rows.Scan(&parentCoilNumber); err != nil {
			return nil, err
		}
		items = append(items, parentCoilNumber)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCoilsForComplaint = `-- name: ListParentCoilsForComplaint :many
SELECT DISTINCT sr."parentCoilNumber"
FROM "ComplaintBatchLine" cbl
INNER JOIN "BatchSlitCoilMap" bcm ON bcm."batchNumber" = cbl."batchNumber"
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = bcm."slitCoilId"
WHERE cbl."complaintId" = $1
`

func (q *Queries) ListParentCoilsForComplaint(ctx context.Context, complaintID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParentCoilsForComplaint, complaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parentCoilNumber string
		if err := rows.Scan(&parentCoilNumber); err != nil {
			return nil, err
		}
		items = append(items, parentCoilNumber)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCoilsForDispatch = `-- name: ListParentCoilsForDispatch :many
SELECT DISTINCT sr."parentCoilNumber"
FROM "DispatchBatchLine" dbl
INNER JOIN "BatchSlitCoilMap" bcm ON bcm."batchNumber" = dbl."batchNumber"
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = bcm."slitCoilId"
WHERE dbl."dispatchNoteNumber" = $1
`

func (q *Queries) ListParentCoilsForDispatch(ctx context.Context, dispatchNoteNumber string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParentCoilsForDispatch, dispatchNoteNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parentCoilNumber string
		if err := rows.Scan(&parentCoilNumber); err != nil {
			return nil, err
		}
		items = append(items, parentCoilNumber)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCoilsForProjectFromComplaint = `-- name: ListParentCoilsForProjectFromComplaint :many
SELECT DISTINCT sr."parentCoilNumber"
FROM "Complaint" c
INNER JOIN "ComplaintBatchLine" cbl ON cbl."complaintId" = c."complaintId"
INNER JOIN "BatchSlitCoilMap" bcm ON bcm."batchNumber" = cbl."batchNumber"
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = bcm."slitCoilId"
WHERE c."projectName" ILIKE $1
`

func (q *Queries) ListParentCoilsForProjectFromComplaint(ctx context.Context, projectName string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParentCoilsForProjectFromComplaint, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parentCoilNumber string
		if err := rows.Scan(&parentCoilNumber); err != nil {
			return nil, err
		}
		items = append(items, parentCoilNumber)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCoilsForProjectFromDispatch = `-- name: ListParentCoilsForProjectFromDispatch :many
SELECT DISTINCT sr."parentCoilNumber"
FROM "SiteDispatch" sd
INNER JOIN "DispatchBatchLine" dbl ON dbl."dispatchNoteNumber" = sd."dispatchNoteNumber"
INNER JOIN "BatchSlitCoilMap" bcm ON bcm."batchNumber" = dbl."batchNumber"
INNER JOIN "SlittingRecord" sr ON sr."slitCoilId" = bcm."slitCoilId"
WHERE sd."projectName" ILIKE $1
`

func (q *Queries) ListParentCoilsForProjectFromDispatch(ctx context.Context, projectName string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParentCoilsForProjectFromDispatch, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parentCoilNumber string
		if err := rows.Scan(&parentCoilNumber); err != nil {
			return nil, err
		}
		items = append(items, parentCoilNumber)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityBatches = `-- name: SearchTraceabilityBatches :many
SELECT "batchNumber", "productType", "productionDate"
FROM "ProductionBatch"
WHERE "batchNumber" ILIKE '%' || $1 || '%'
ORDER BY "productionDate" DESC
LIMIT $2
`

type SearchTraceabilityBatchesParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityBatchesRow struct {
	BatchNumber    string           `json:"batchNumber"`
	ProductType    string           `json:"productType"`
	ProductionDate pgtype.Timestamp `json:"productionDate"`
}

func (q *Queries) SearchTraceabilityBatches(ctx context.Context, arg SearchTraceabilityBatchesParams) ([]SearchTraceabilityBatchesRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityBatches, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityBatchesRow{}
	for rows.Next() {
		var i SearchTraceabilityBatchesRow
		if err := rows.Scan(&i.BatchNumber, &i.ProductType, &i.ProductionDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityCoils = `-- name: SearchTraceabilityCoils :many
SELECT "coilNumber", grade, coating, "createdAt"
FROM "Coil"
WHERE "coilNumber" ILIKE '%' || $1 || '%'
ORDER BY "createdAt" DESC
LIMIT $2
`

type SearchTraceabilityCoilsParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityCoilsRow struct {
	CoilNumber string           `json:"coilNumber"`
	Grade      string           `json:"grade"`
	Coating    string           `json:"coating"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) SearchTraceabilityCoils(ctx context.Context, arg SearchTraceabilityCoilsParams) ([]SearchTraceabilityCoilsRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityCoils, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityCoilsRow{}
	for rows.Next() {
		var i SearchTraceabilityCoilsRow
		if err := rows.Scan(
			&i.CoilNumber,
			&i.Grade,
			&i.Coating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityComplaints = `-- name: SearchTraceabilityComplaints :many
SELECT "complaintId", "projectName", "resolutionStatus"::text AS resolution_status, "complaintDate"
FROM "Complaint"
WHERE "complaintId" ILIKE '%' || $1 || '%'
   OR "projectName" ILIKE '%' || $1 || '%'
ORDER BY "complaintDate" DESC
LIMIT $2
`

type SearchTraceabilityComplaintsParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityComplaintsRow struct {
	ComplaintId      string           `json:"complaintId"`
	ProjectName      string           `json:"projectName"`
	ResolutionStatus string           `json:"resolution_status"`
	ComplaintDate    pgtype.Timestamp `json:"complaintDate"`
}

func (q *Queries) SearchTraceabilityComplaints(ctx context.Context, arg SearchTraceabilityComplaintsParams) ([]SearchTraceabilityComplaintsRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityComplaints, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityComplaintsRow{}
	for rows.Next() {
		var i SearchTraceabilityComplaintsRow
		if err := rows.Scan(
			&i.ComplaintId,
			&i.ProjectName,
			&i.ResolutionStatus,
			&i.ComplaintDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityComplaintsByProject = `-- name: SearchTraceabilityComplaintsByProject :many
SELECT "complaintId", "projectName", "resolutionStatus"::text AS resolution_status
FROM "Complaint"
WHERE "projectName" ILIKE '%' || $1 || '%'
ORDER BY "complaintDate" DESC
LIMIT $2
`

type SearchTraceabilityComplaintsByProjectParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityComplaintsByProjectRow struct {
	ComplaintId      string `json:"complaintId"`
	ProjectName      string `json:"projectName"`
	ResolutionStatus string `json:"resolution_status"`
}

func (q *Queries) SearchTraceabilityComplaintsByProject(ctx context.Context, arg SearchTraceabilityComplaintsByProjectParams) ([]SearchTraceabilityComplaintsByProjectRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityComplaintsByProject, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityComplaintsByProjectRow{}
	for rows.Next() {
		var i SearchTraceabilityComplaintsByProjectRow
		if err := rows.Scan(&i.ComplaintId, &i.ProjectName, &i.ResolutionStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityDispatches = `-- name: SearchTraceabilityDispatches :many
SELECT "dispatchNoteNumber", "projectName", "dispatchDate"
FROM "SiteDispatch"
WHERE "dispatchNoteNumber" ILIKE '%' || $1 || '%'
   OR "projectName" ILIKE '%' || $1 || '%'
ORDER BY "dispatchDate" DESC
LIMIT $2
`

type SearchTraceabilityDispatchesParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityDispatchesRow struct {
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	ProjectName        string           `json:"projectName"`
	DispatchDate       pgtype.Timestamp `json:"dispatchDate"`
}

func (q *Queries) SearchTraceabilityDispatches(ctx context.Context, arg SearchTraceabilityDispatchesParams) ([]SearchTraceabilityDispatchesRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityDispatches, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityDispatchesRow{}
	for rows.Next() {
		var i SearchTraceabilityDispatchesRow
		if err := rows.Scan(&i.DispatchNoteNumber, &i.ProjectName, &i.DispatchDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilityDispatchesByProject = `-- name: SearchTraceabilityDispatchesByProject :many
SELECT "dispatchNoteNumber", "projectName", "dispatchDate"
FROM "SiteDispatch"
WHERE "projectName" ILIKE '%' || $1 || '%'
ORDER BY "dispatchDate" DESC
LIMIT $2
`

type SearchTraceabilityDispatchesByProjectParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilityDispatchesByProjectRow struct {
	DispatchNoteNumber string           `json:"dispatchNoteNumber"`
	ProjectName        string           `json:"projectName"`
	DispatchDate       pgtype.Timestamp `json:"dispatchDate"`
}

func (q *Queries) SearchTraceabilityDispatchesByProject(ctx context.Context, arg SearchTraceabilityDispatchesByProjectParams) ([]SearchTraceabilityDispatchesByProjectRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilityDispatchesByProject, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilityDispatchesByProjectRow{}
	for rows.Next() {
		var i SearchTraceabilityDispatchesByProjectRow
		if err := rows.Scan(&i.DispatchNoteNumber, &i.ProjectName, &i.DispatchDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraceabilitySlits = `-- name: SearchTraceabilitySlits :many
SELECT "slitCoilId", "parentCoilNumber", "slittingDate"
FROM "SlittingRecord"
WHERE "slitCoilId" ILIKE '%' || $1 || '%'
ORDER BY "slittingDate" DESC
LIMIT $2
`

type SearchTraceabilitySlitsParams struct {
	SearchTerm  pgtype.Text `json:"search_term"`
	ResultLimit int32       `json:"result_limit"`
}

type SearchTraceabilitySlitsRow struct {
	SlitCoilId       string           `json:"slitCoilId"`
	ParentCoilNumber string           `json:"parentCoilNumber"`
	SlittingDate     pgtype.Timestamp `json:"slittingDate"`
}

func (q *Queries) SearchTraceabilitySlits(ctx context.Context, arg SearchTraceabilitySlitsParams) ([]SearchTraceabilitySlitsRow, error) {
	rows, err := q.db.Query(ctx, searchTraceabilitySlits, arg.SearchTerm, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTraceabilitySlitsRow{}
	for rows.Next() {
		var i SearchTraceabilitySlitsRow
		if err := rows.Scan(&i.SlitCoilId, &i.ParentCoilNumber, &i.SlittingDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
