// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdminsExcept = `-- name: CountActiveAdminsExcept :one
SELECT COUNT(*)::bigint AS count
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE u."isActive" = true
  AND r.code = 'ADMIN'
  AND u.id != $1
`

func (q *Queries) CountActiveAdminsExcept(ctx context.Context, excludeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsExcept, excludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" (
    id,
    email,
    "passwordHash",
    "fullName",
    "roleId",
    "createdAt",
    "updatedAt"
)
VALUES (
    $1,
    LOWER($2),
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, email, "fullName", "isActive", "createdAt", "roleId"
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
	RoleID       string `json:"role_id"`
}

type CreateUserRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	FullName  string           `json:"fullName"`
	IsActive  bool             `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	RoleId    string           `json:"roleId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.RoleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.RoleId,
	)
	return i, err
}

const findUserIDByEmailExcluding = `-- name: FindUserIDByEmailExcluding :one
SELECT id
FROM "User"
WHERE LOWER(email) = LOWER($1)
  AND id != $2
`

type FindUserIDByEmailExcludingParams struct {
	Email     string `json:"email"`
	ExcludeID string `json:"exclude_id"`
}

func (q *Queries) FindUserIDByEmailExcluding(ctx context.Context, arg FindUserIDByEmailExcludingParams) (string, error) {
	row := q.db.QueryRow(ctx, findUserIDByEmailExcluding, arg.Email, arg.ExcludeID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserPublicByID = `-- name: GetUserPublicByID :one
SELECT
    u.id,
    u.email,
    u."fullName",
    u."isActive",
    u."createdAt",
    r.code AS role_code,
    r.name AS role_name
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE u.id = $1
`

type GetUserPublicByIDRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	FullName  string           `json:"fullName"`
	IsActive  bool             `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	RoleCode  string           `json:"role_code"`
	RoleName  string           `json:"role_name"`
}

func (q *Queries) GetUserPublicByID(ctx context.Context, id string) (GetUserPublicByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicByID, id)
	var i GetUserPublicByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const getUserWithRoleByID = `-- name: GetUserWithRoleByID :one
SELECT
    u.id,
    u.email,
    u."fullName",
    u."isActive",
    u."roleId",
    r.code AS role_code
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
WHERE u.id = $1
`

type GetUserWithRoleByIDRow struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	IsActive bool   `json:"isActive"`
	RoleId   string `json:"roleId"`
	RoleCode string `json:"role_code"`
}

func (q *Queries) GetUserWithRoleByID(ctx context.Context, id string) (GetUserWithRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRoleByID, id)
	var i GetUserWithRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.RoleId,
		&i.RoleCode,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    u.id,
    u.email,
    u."fullName",
    u."isActive",
    u."createdAt",
    r.code AS role_code,
    r.name AS role_name
FROM "User" u
INNER JOIN "Role" r ON r.id = u."roleId"
ORDER BY u."fullName" ASC
`

type ListUsersRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	FullName  string           `json:"fullName"`
	IsActive  bool             `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	RoleCode  string           `json:"role_code"`
	RoleName  string           `json:"role_name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "User"
SET
    email = COALESCE($1, email),
    "fullName" = COALESCE($2, "fullName"),
    "isActive" = COALESCE($3, "isActive"),
    "roleId" = COALESCE($4, "roleId"),
    "passwordHash" = COALESCE($5, "passwordHash"),
    "updatedAt" = NOW()
WHERE id = $6
RETURNING id, email, "fullName", "isActive", "createdAt", "roleId"
`

type UpdateUserParams struct {
	Email        pgtype.Text `json:"email"`
	FullName     pgtype.Text `json:"full_name"`
	IsActive     pgtype.Bool `json:"is_active"`
	RoleID       pgtype.Text `json:"role_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           string      `json:"id"`
}

type UpdateUserRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	FullName  string           `json:"fullName"`
	IsActive  bool             `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	RoleId    string           `json:"roleId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FullName,
		arg.IsActive,
		arg.RoleID,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.RoleId,
	)
	return i, err
}
